apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: victoria-metrics-k8s-stack
  namespace: victoria-metrics
spec:
  interval: 10m
  chart: victoria-metrics-k8s-stack
  sourceRef:
    kind: HelmRepository
    name: victoria-metrics
  version: "0.67.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: victoria-metrics
spec:
  interval: 1m0s
  chartRef:
    kind: HelmChart
    name: victoria-metrics-k8s-stack
    namespace: victoria-metrics
  values:
    victoria-metrics-operator:
      enabled: true
      image:
        repository: victoriametrics/operator
        tag: "v0.66.1"
      crds:
        enabled: true
        cleanup:
          enabled: true
        upgrade:
          enabled: true
          forceConflicts: true
      operator:
        disable_prometheus_converter: true
        service:
          httpsPort: 9443
        tls:
          auto: true
      serviceMonitor:
        enabled: false
    grafana:
      enabled: true
      existingSecret: grafana
      admin:
        existingSecret: grafana
        userKey: admin-user
        passwordKey: admin-password
      forceDeployDatasource: true
      image:
        repository: grafana/grafana
        tag: "12.2.1"
      ingress:
        enabled: true
        ingressClassName: ksbh
        hosts:
          - vm-gr.kys.dog
        annotations:
          ksbh.rs/modules: "oidc-authentik"
        tls:
          - hosts:
            - vm-gr.kys.dog
            secretName: kys-dog
      persistence:
        enabled: true
        type: pvc
        size: 32Gi
        storageClassName: longhorn
      plugins:
        - victoriametrics-metrics-datasource
        - victoriametrics-logs-datasource
    vmsingle:
      enabled: true
      service:
        enabled: true
        type: ClusterIP
      spec:
        port: "8428"
        retentionPeriod: "1"
        storage:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 64Gi
      ingress:
        enabled: true
        ingressClassName: ksbh
        hosts:
          - vm.kys.dog
        annotations:
          ksbh.rs/modules: "oidc-authentik"
        tls:
          - hosts:
            - vm.kys.dog
            secretName: kys-dog
    vmalert:
      enabled: true
      service:
        enabled: true
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: ksbh
        hosts:
          - vm-al.kys.dog
        annotations:
          ksbh.rs/modules: "oidc-authentik"
        tls:
          - hosts:
            - vm-al.kys.dog
            secretName: kys-dog
    vmagent:
      enabled: true
      service:
        enabled: true
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: ksbh
        hosts:
          - vm-ag.kys.dog
        annotations:
          ksbh.rs/modules: "oidc-authentik"
        tls:
          - hosts:
            - vm-ag.kys.dog
            secretName: kys-dog
      extraScrapeConfigs:
        - job_name: 'k8s-services'
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_label_victoria_metrics_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_service_name]
              target_label: job
            - source_labels: [__meta_kubernetes_endpoint_address_target_name, __meta_kubernetes_endpoint_port_name]
              separator: ":"
              target_label: instance
    alertmanager:
      enabled: true
      service:
        enabled: true
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: ksbh
        hosts:
          - vm-am.kys.dog
        annotations:
          ksbh.rs/modules: "oidc-authentik"
        tls:
          - hosts:
            - vm-am.kys.dog
            secretName: kys-dog
    defaultDatasources:
      victoriametrics:
        perReplica: true
      alertmanager:
        perReplica: true
        datasources:
          - name: Alertmanager
            access: proxy
            jsonData:
              implementation: prometheus
      grafanaOperator:
        enabled: false
    defaultScrapeService:
      namespace: kube-system
    prometheus-node-exporter:
      enabled: true
      vmScrape:
        enabled: true
    kube-state-metrics:
      enabled: true
    kubelet:
      enabled: true
    kubeApiServer:
      enabled: true
    kubeControllerManager:
      enabled: true
    kubeDns:
      enabled: false
    coreDns:
      enabled: true
    kubeEtcd:
      enabled: true
    kubeScheduler:
      enabled: true
    kubeProxy:
      enabled: false

