apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  ports:
    - protocol: TCP
      name: gitlab-web
      port: 9001
  selector:
    app: gitlab
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ssh
  namespace: gitlab
  labels:
    app: gitlab-ssh

spec:
  type: LoadBalancer
  loadBalancerIP: 10.15.25.40
  externalTrafficPolicy: Local
  ports:
    - name: gitlab-ssh
      port: 10022
      targetPort: 22
  selector:
    app: gitlab

