apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
    name: discord-bot-minecraft-whitelister
    namespace: tools
spec:
    imageRepositoryRef:
        name: discord-bot-minecraft-whitelister
    filterTags:
        pattern: "^[a-f0-9]+-(?P<ts>[0-9]+)"
        extract: "$ts"
    policy:
        numerical:
            order: asc
