apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik
  namespace: tools
spec:
  name: authentik
  owner: authentik
  cluster:
    name: global-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: gitlab
  namespace: tools
spec:
  name: gitlab
  owner: gitlab
  cluster:
    name: global-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: mailu
  namespace: tools
spec:
  name: mailu
  owner: mailu
  cluster:
    name: global-pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: kong
  namespace: tools
spec:
  name: kong
  owner: kong
  cluster:
    name: global-pg
