# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmchart-source-v1.json
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  interval: 10m
  chart: gitlab-runner
  sourceRef:
    kind: HelmRepository
    name: gitlab
  version: "v0.83.2"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
    interval: 1m0s
    chartRef:
      kind: HelmChart
      name: gitlab-runner
      namespace: gitlab
    install:
        remediation:
            retries: 100
    values:
        replicas: 1
        concurrent: 50
        hostAliases:
            - ip: "10.15.25.100"
              hostnames:
                  - "git.yannis.codes"
            - ip: "10.15.25.40"
              hostnames:
                  - "ssh.git.yannis.codes"
        rbac:
            create: true
        gitlabUrl: https://git.yannis.codes
        serviceAccount:
          create: true
          imagePullSecrets:
            - gitlab-runners-harbor-auth
        runners:
            secret: gitlab-runner
            namespace: gitlab
            imagePullSecrets:
              - name: gitlab-runners-harbor-auth
            cache:
                secretName: "s3-garage-access"
                cacheShared: true
            config: |
                [[runners]]
                  executor = "kubernetes"
                  service_account = "gitlab-runner"
                  pre_clone_script = "git config --global http.proxy $HTTP_PROXY; git config --global https.proxy $HTTPS_PROXY"
                  environment = [
                    "FF_KUBERNETES_HONOR_ENTRYPOINT=true",
                    "http_proxy=http://squid.vlan.internal.nether:3128",
                    "https_proxy=http://squid.vlan.internal.nether:3128",
                    "HTTP_PROXY=http://squid.vlan.internal.nether:3128",
                    "HTTPS_PROXY=http://squid.vlan.internal.nether:3128",
                    "no_proxy=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local,git.yannis.codes,.internal.nether,.internal.yannis.codes",
                    "NO_PROXY=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local,git.yannis.codes,.internal.nether,.internal.yannis.codes"
                  ]
                  [runners.cache]
                    Type = "s3"
                    Path = "/"
                    Shared = true
                  [runners.cache.s3]
                    ServerAddress = "garage.s3.internal.yannis.codes"
                    BucketName = "longhorn-bucket"
                    BucketLocation = "hetzner"
                    Insecure = false
                  [runners.kubernetes]
                    namespace = "gitlab"
                    privileged = false
                    allowPrivilegeEscalation = true
                    use_service_account_image_pull_secrets = true
                    [[runners.kubernetes.volumes.secret]]
                      name = "gitlab-runners-harbor-auth"
                      mount_path = "/root/.docker"
                      read_only = true
                      [runners.kubernetes.volumes.secret.items]
                        ".dockerconfigjson" = "config.json"
                    [runners.kubernetes.pod_annotations]
                      "container.apparmor.security.beta.kubernetes.io/build" = "unconfined"
                      "container.seccomp.security.alpha.kubernetes.io/build" = "unconfined"
                    [runners.kubernetes.build_container_security_context]
                      [runners.kubernetes.build_container_security_context.capabilities]
                        add = ["SETGID", "SETUID"]
                    [runners.kubernetes.affinity]
                      [runners.kubernetes.affinity.node_affinity]
                        [runners.kubernetes.affinity.node_affinity.required_during_scheduling_ignored_during_execution]
                          [[runners.kubernetes.affinity.node_affinity.required_during_scheduling_ignored_during_execution.node_selector_terms]]
                            [[runners.kubernetes.affinity.node_affinity.required_during_scheduling_ignored_during_execution.node_selector_terms.match_expressions]]
                              key = "usage"
                              operator = "In"
                              values = ["worker"]
