apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: tools
data:
  config.alloy: |
    discovery.kubernetes "all_pods" {
      role = "pod"
    }

    discovery.relabel "filtered" {
      targets = discovery.kubernetes.all_pods.targets

      rule {
        source_labels = ["__meta_kubernetes_pod_label_pyroscope_profiling"]
        regex = "enabled"
        action = "keep"
      }

      rule { action = "drop" }
    }

    pyroscope.ebpf "profile_selected" {
      forward_to = [pyroscope.write.local.receiver]
      targets    = discovery.relabel.filtered.output
    }

    pyroscope.write "local" {
      endpoint {
        url = "http://pyroscope.tools.svc.cluster.local:4040"
      }
    }

