apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: pyroscope
  namespace: tools
spec:
  interval: 10m
  chart: pyroscope
  sourceRef:
    kind: HelmRepository
    name: grafana
  version: "1.17.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pyroscope
  namespace: tools
spec:
  interval: 1m0s
  chartRef:
    kind: HelmChart
    name: pyroscope
    namespace: tools
  values:
    pyroscope:
      replicaCount: 1
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 24Gi
        existingClaim: pyroscope-pvc
      extraArgs:
        log.level: debug
      overwriteResources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 1024Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: usage
                    operator: In
                    values:
                      - worker
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
    alloy:
      enabled: true
      controller:
        type: statefulset
        replicas: 1
      alloy:
        stabilityLevel: public-preview
        configMap:
          create: false
          name: alloy-config
        clustering:
          enabled: true
