apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parca-agent
  namespace: tools
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: parca-agent
  namespace: tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: parca-agent
subjects:
- kind: ServiceAccount
  name: parca-agent
  namespace: tools
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parca-agent
  namespace: tools
data:
  parca-agent.yaml: |-
    relabel_configs:
    - source_labels: ["__meta_kubernetes_pod_label_parca_profiling"]
      regex: "enabled"
      action: keep
    - source_labels: ["__meta_kubernetes_namespace"]
      target_label: "namespace"
    - source_labels: ["__meta_kubernetes_pod_name"]
      target_label: "pod"
    - source_labels: ["__meta_kubernetes_pod_container_name"]
      target_label: "container"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: parca-agent
  namespace: tools
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: parca-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: parca-agent
    spec:
      nodeSelector:
        role: worker
      hostPID: true
      serviceAccountName: parca-agent
      containers:
      - name: parca-agent
        image: ghcr.io/parca-dev/parca-agent:v0.44.2
        args:
        - --node=$(NODE_NAME)
        - --config-path=/etc/parca-agent/parca-agent.yaml
        - --remote-store-address=parca.tools.svc.cluster.local:7070
        - --remote-store-insecure
        - --profiling-cpu-sampling-frequency=11
        - --mem-limit=128M
        - --debuginfo-strip=true
        - --debuginfo-upload-max-parallel=1
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/parca-agent
          name: config
        - mountPath: /run
          name: run
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/bpf
          name: bpffs
      volumes:
      - name: config
        configMap:
          name: parca-agent
      - name: run
        hostPath:
          path: /run
      - name: modules
        hostPath:
          path: /lib/modules
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: parca-agent
  namespace: tools
