apiVersion: v1
kind: ConfigMap
metadata:
  name: parca-agent
  namespace: tools
  labels:
    app.kubernetes.io/name: parca-agent
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca-agent
    app.kubernetes.io/version: v0.44.2
data:
  parca-agent.yaml: |-
    relabel_configs:
      - action: keep
        source_labels: ["__meta_kubernetes_pod_label_parca_profiling"]
        regex: enabled
      - source_labels: ["__meta_process_executable_compiler"]
        target_label: compiler
      - source_labels: ["__meta_system_kernel_machine"]
        target_label: arch
      - source_labels: ["__meta_system_kernel_release"]
        target_label: kernel_version
      - source_labels: ["__meta_kubernetes_namespace"]
        target_label: namespace
      - source_labels: ["__meta_kubernetes_pod_name"]
        target_label: pod
      - source_labels: ["__meta_kubernetes_pod_container_name"]
        target_label: container
      - source_labels: ["__meta_kubernetes_pod_container_image"]
        target_label: container_image
      - source_labels: ["__meta_kubernetes_node_label_topology_kubernetes_io_region"]
        target_label: region
      - source_labels: ["__meta_kubernetes_node_label_topology_kubernetes_io_zone"]
        target_label: zone
      - action: labelmap
        regex: "__meta_kubernetes_pod_label_(.+)"
      - action: labeldrop
        regex: "apps_kubernetes_io_pod_index|controller_revision_hash|statefulset_kubernetes_io_pod_name|pod_template_hash"

    scrape_configs:
      - job_name: kubernetes-services-pprof
        scrape_interval: 15s
        scrape_timeout: 10s
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - action: keep
            source_labels: ["__meta_kubernetes_service_label_parca_profiling"]
            regex: enabled
          - action: keep
            source_labels: ["__meta_kubernetes_endpoint_port_name"]
            regex: profiling
          - source_labels: ["__address__"]
            target_label: __address__
          - source_labels: ["__meta_kubernetes_namespace"]
            target_label: namespace
          - source_labels: ["__meta_kubernetes_service_name"]
            target_label: service
          - action: labelmap
            regex: "__meta_kubernetes_service_label_(.+)"
          - action: labeldrop
            regex: "__meta_kubernetes_endpoint_(.+)"

    profiling_config:
      pprof_config:
        http_pprof:
          enabled: true
          path: /debug/pprof
          delta: false
          interval: 30s
          scheme: http

