apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: image-automation-controller
      namespace: flux-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --log-level=debug
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: image-reflector-controller
      namespace: flux-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --log-level=debug
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                env:
                  - name: "HTTP_PROXY"
                    value: "http://squid.vlan.internal.nether:3128"
                  - name: "HTTPS_PROXY"
                    value: "http://squid.vlan.internal.nether:3128"
                  - name: "NO_PROXY"
                    value: "127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local,.internal.nether,.flux-system.svc.cluster.local,.flux-system.svc.cluster.local.,.internal.yannis.codes"
                  - name: "http_proxy"
                    value: "http://squid.vlan.internal.nether:3128"
                  - name: "https_proxy"
                    value: "http://squid.vlan.internal.nether:3128"
                  - name: "no_proxy"
                    value: "127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local,.internal.nether,.flux-system.svc.cluster.local,.flux-system.svc.cluster.local.,.internal.yannis.codes"
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
