apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions:
    - vers=4.2
    - proto=tcp
    - hard
    - noatime
  nfs:
    server: nfs.vlan.internal.nether
    path: /srv/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  volumeName: media-nfs
  resources:
    requests:
      storage: 2Ti
