apiVersion: batch/v1
kind: Job
metadata:
  name: charts-ksbh-rs
  namespace: ksbh
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sync
          image: harbor.internal.yannis.codes/registry/ksbh-charts:9bb45de8d65b-20260324182712 # {"$imagepolicy": "ksbh:ksbh-charts"}
          command:
            - /bin/sh
            - -ec
            - |
              test -d /payload
              rm -rf /data/static/charts.ksbh.rs
              mkdir -p /data/static/charts.ksbh.rs
              cp -a /payload/. /data/static/charts.ksbh.rs
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ksbh-data
