apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml

  - ./valkey/helm-release.yaml
  - ./valkey/helm-repository.yaml

  - ./cloudnative-pg/cluster.yaml
  - ./cloudnative-pg/databases.yaml
  - ./cloudnative-pg/helm-repository.yaml
  - ./cloudnative-pg/operator/helm-release.yaml

  - ./reflector/helm-release.yaml
  - ./reflector/helm-repo.yaml

  - ./pyroscope/helm-release.yaml
  - ./pyroscope/helm-repository.yaml

  - ./discord-mc-whitelister/deployment.yaml
  - ./discord-mc-whitelister/persistent-volume.yaml
  - ./discord-mc-whitelister/persistent-volume-claim.yaml
  - ./discord-mc-whitelister/flux-image/image-policy.yaml
  - ./discord-mc-whitelister/flux-image/image-repository.yaml
  - ./discord-mc-whitelister/flux-image/image-update-automation.yaml
