apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml

  - ./cloudnative-pg/cluster.yaml
  - ./cloudnative-pg/databases.yaml
  - ./cloudnative-pg/helm-repository.yaml
  - ./cloudnative-pg/operator/helm-release.yaml

  - ./reflector/helm-release.yaml
  - ./reflector/helm-repo.yaml

  - ./fizzy/service.yaml
  - ./fizzy/deployment.yaml
  - ./fizzy/http-route.yaml
