apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mailu-certs
  namespace: mailu
spec:
  secretName: mailu-certs
  additionalOutputFormats:
    - type: CombinedPEM
    - type: DER
  dnsNames:
    - 'yannis.codes'
    - 'mail.yannis.codes'
    - 'mail.internal.yannis.codes'
    - 'kys.dog'
    - 'ksbh.rs'
  issuerRef:
    name: le-prod
    kind: ClusterIssuer

