apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:fiQa+HpO3F7iQX3BW3n2eHcXCTRQLEkipSOFudQpnw26ZHmIQ5s=,iv:ONjIVwcR8gfCEwbo33y4u+BSAMKht4dwHSbkj6BUIOg=,tag:4efYriBow2qMMdrZ6InEGQ==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:tV+230S0mPuUDqW4hn3ErqE8dxjOwDS2aG6Am7ZDg8lQ6p61ZuriNg==,iv:+t5Agu0HJRScatvAlQmeJOoIEDgyfBXiO1aVD53GwVE=,tag:+ZHjFuRls1XxIVF7EDjiiw==,type:str]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:ngsNoH/d0blefIrpHky4p+nkDerpFA==,iv:UjcZSZEX5f/ipdLgzK+Dl9u4ymehgei0toFZiS2M+IA=,tag:0kTGlmWIvNSq3P7yy2n8zw==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:KXLggKWHis8YMkBBSE3UuSX3K/AxWKWF/XI2FK4QmAXulWCJ,iv:a8qKv7rRpjW4HogMXSGFDjkreC9Dk1g1SOjjGfOA+us=,tag:T9/XmoaDG23xmyCX2XVI4g==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:Sglzkw==,iv:xOOmJ3rzhdjp5XESTVu8qKSxmL4Lyrk9z+2PNUvMX/k=,tag:aEyiiTJ8kxS0fOSmIiHjHQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:wWouvdp9YJgS,iv:UK+2SCLdyGQvuyqW9LBrWNwkMEbZ+eUonq+TF5M0+y4=,tag:048PltEW/nNdYuHr1tDIjQ==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:+2tYnr8eTjgH,iv:B0CsrYgD5iTWFRz/HxUgdZXWzlDpqBPlxAxV4bGsJKE=,tag:xbopQssuZqErVyzSfYIEbQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:tiawxZLuN0AObZZFddlTJ7L6jauR63YATmdPtcp1acjK/eL3Tlj4fN8QR0DrF8B/9w==,iv:JIW0YkaRslL6KrmQfR57jlijf50SLh6nQ/XX/lQF1PY=,tag:ZiAkqdnhdwm50JNl+88Uvw==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:GDJ4T/nUKnxs4pUMWt6WNw4=,iv:d8Lzoo1+3zG9P0YnkbIMAugs21rmTqPwSeyoBKEvd20=,tag:zsM8HJ8FFQGij77GHZnUJA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:NLFTclGbr+x2MK5qGVWGTQpGBBQqclnZv3XrsmSzp0M7FpuG9iqonFg=,iv:6SwxrLDffZ2Z8euB7Ik05msLrfPDXH5hX5ZvlpEhkTg=,tag:os8cXG8wJ4RSznSyb3qsmA==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOEpRM28wNzlXVm0zQUp1
            SjU0bWlMNWVUaXJTUjA2Q1F3TGdZN3lWUVVVCnhtWlFDUGx0YTZ1bUJvU0V5cW1S
            eHhBZGlOc2JYRlh0VDJjOFM2cXhrRHMKLS0tIFhiOTRRdjRCUWpleUtJZERDS3V6
            ZXh2anNCZTZ5L1o0eHd3N0RxS2VJOFEKZHtKgD5l+H2HKkg24bKuKN8vshkvWDnR
            tCHsP2wLS6LQapSricfOLpDTHbbzHaetABS+jI4yo+vPtEOqa0Ah+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T17:34:10Z"
    mac: ENC[AES256_GCM,data:RCjLKlr/HFy0pZP24AcW5ZDyi5lt8/uTx76rCS1yF3WlZLgrJnRWA3tTfplcBsGz5/RRy6eR9aYQQf3hVWehdLGnP4OKc5PZDYSJvq3Hen/stiPVz7nByYBbO0JfHt0Fqy/6lkPSzUODeHMadxjavOMyR6EnELCOEOlVj69/yJg=,iv:yvAZOf93PbC2T7FPqdETpQ1/u78Sgc/Ttuq5WaAbmVU=,tag:tvlTGjHqq5TamSSznHiheQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
