apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:WXEQkLBkGI4zN7Y0aLvdQEXp4TzEh4nYRPHeGW0E6MneV6idIgg=,iv:jQWniFl1oe2xQ+9C1pXICo3TQMZD35cQb4sHA282f34=,tag:F8KaeffYLk+EFFxMLNyy0g==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:0a/9p8EDgV8GYrJKj0MOVY+hgMfn3Fl2ENiw52Tll9WEUPAAaq2ISw==,iv:nx4v2wYDNzpMHuBx7gWK7lMdQJR6bpHMbUfWLII8zKs=,tag:rivjQ3FSXhjNtrDoexlfbg==,type:str]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:IS0V1F5pcTz6hl9waxTYR834uovJ/g==,iv:kChkrHfWa4B8CpMHbL1UiKX7sj93Xxt673LrFGPX4Mg=,tag:bkbeKpPkvw6e0b2pXWq6gA==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVUpkaVJiVzZKWWN5V1lm
            MWNXWWdzUkdaMDFrWVI2L3BlenZDeThhc25nClYzdmxGaFhrUnJMVzNMTkR4UVU5
            SzVDK0U1UFpGUjUycjVtRm95UVJvdFUKLS0tIGNSUHF1aWhLL244dlhEWFdVSEht
            VFFVczZEc0plM0N0d0RpK3hTUXZIQWMKqq/zRqR4U151AZyB1IVYx1t4l7SfFkQI
            9iL5TjpwM2AgBVVgkOAg6n+txTpQKeixuZIYCHwhtklaBRoCSzGy6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T17:45:06Z"
    mac: ENC[AES256_GCM,data:1co+yZdGT3qvAb0Rpn/iDOTWh3KbRoBBG/rKx/1AGRS97z1HuHiOeXelEwa/PjtBYTon8b+dBnMgmFteAw/a+VZ89PEinhnJDbFUFgjyDZHfu+EIHCqPAzKNt1a9CjNYgGWQfJSfPt41CuYqA2F2rgKajm4Nxqv4jYLxpL9COik=,iv:BQVESpWVVT0sV+Yo7bU4bN9egooAlwv/b2JkUa7TyGc=,tag:yYlGIG8ZbMqVtO1TZ18gnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
