apiVersion: v1
kind: Secret
metadata:
    name: fizzy-secrets
    namespace: tools
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:IzWqRcQEP3qz9LbhzdfvS3UF5pjuZFda3iA1rGg6zG1JN4Bc2kJmt9N/V92ZvxMZIS7O0pBfjLybvfUa9hLxteJ9O3SP3/10NesC/mCMBUDoboD1GA5lA/linuq6gMIgYtsWEXjwvZZfDwfSKu2o,iv:YfOhBohFUS4Ncb39KVut893/WiP//gv4uQ5wXVxbnKU=,tag:Avb8HcJnBkO90BiYj/dG5g==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:IzjeAh1T/wVuvri3eBUuyD2gEjkyhAXYv2MJVYnNbmZWf7AqyOAWNuz5tQ==,iv:lgxIDQjZCv8EgX4tbODReV8KGG8uKCNk44za7J7ZmX8=,tag:kcU/yK5ckDqPwnFSDv1kwQ==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:PLoBYp5rT0b38nlI64EGi5GLDeGDiUAVQTTJPblCZn8QeErG/aRKfEUyrBtrVOCER+ftdtJwbFUosq2H4Dk0ZS7l9lOpKOK9cEVfY8qV5HDHf9s4Uhv2,iv:YRr6zxvi/Jf20JJqhp0wPMKD87S85NcHFLmALbCJtK8=,tag:lkEJpmH1hgTsEfHPE/OCZw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:XSqq4qfUaACBmSpW5X8qToFD,iv:r8hDasP3q6EynOQ+jvhpPQD+6bJkLsSJxYuojyVYHX8=,tag:l0hBqei9/n+GclOX9IzLdg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:cEid9HZrz6FgShg/0jO95jQzoHFUKMTU1i3tTW7wBQ11eLmov0Nvk+9KIAtaH782,iv:cquFsd6N4qVuTbXGBbnWkVrrDDODzDlHt1N2cAtVOGI=,tag:Ms2jRfMWTxqxORF63KXgyw==,type:str]
    MAILER_FROM_ADDRESS: ENC[AES256_GCM,data:ga2fdI82EDNDGpf5BpxxFCCJ,iv:/CkiRLtSMpJhoc7VqT8RRWRCeWDpkwmSok5jfjD1mPY=,tag:TvqG8+ySF00DoX60shYNkg==,type:str]
    SMTP_ADDRESS: ENC[AES256_GCM,data:TLf6LLNwCgbaHAu1Uly7mss=,iv:AstkIfxiviCS8QIFJsoAWgaVkXB/e5LWNSioiqMXYh8=,tag:CrtECPyX7V9rVg2xBmUaPw==,type:str]
    SMTP_DOMAIN: ENC[AES256_GCM,data:vxAotgZ6V5uZUYV0LtXKDjo=,iv:L5o7YTppWgTFBbKEn1ip5vzkuz0ojm9yMLrAjtI4ak4=,tag:XEFsroY01dSdMdourvVRng==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:ZsSk,iv:1QD+6oLlc/oghdzIg5ZaKQ3bqc+z68Oph9q0Z57s8Zk=,tag:78rJmnJixKF+sbj77VP0mw==,type:int]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTU9JTE13SjBkSjBxbzMz
            V01aQ3hvdVp5Y01XaFI1cjl6MkQ0Znlvb0cwCmJ0dyt2RnlBenhoRzBRVGc1ejJ5
            YlRBMkJ4dUIxYjVwNmRUV1ZHdGtUMXcKLS0tIEFidjNIdkMvM3FFWjNPSG96WXpZ
            ZVdDZGg2ak9IZHR4WHNaUDQvdnJNOGsKSK+JFppowO5eAtGqrnoslcNYNMD8R+Oc
            E4ReNQPve3rQOAl9AbLSjXdEJmgzoqVBjdWUP+LTRJmxD1+y+KxCOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T17:30:08Z"
    mac: ENC[AES256_GCM,data:x6yXdqE4LM0EzdAyj89eADhlIpTC82R9YeBCv/QFEjCchlBcOUMRbrqVDMgN6f6X2Q/B61aXrdpWhz6DYx1TYOjkrDl/iqKkHarxEpt1grOuYr79TYaTmfQ2FM76gkmHSfcVOOcoFdKT5oOozqKyRCBeH1dtknwjhWKFONrlQX0=,iv:HdT9DcFgL2mZM8V67p6tJaFznSo2Eyr7b35FPHHl8qs=,tag:94l61M7TCk4YaarIZFDNhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
