apiVersion: v1
kind: Secret
metadata:
    name: fizzy-secrets
    namespace: tools
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:KC43WjCoEFHnXktwS84a24ZZ2rqbd2keagUAaVxKAiA59RkxGEaUrD713cBxKw6ZjbCXLVTl5W0RJsaNAbljaMFj+KXmpiWXPe4hXFpP9Y83JNjKOBubfUgFmhG8HuthLUk76lKH0Xg8lfvXaACk,iv:jf8yGaHi+w0PwpuyKVgvYVBDgryXDDQ8FpfCNVOdscw=,tag:sSWtjRcColUyoJJU4vhXdQ==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:SRGrkTQ2HmG2GT0HAtxq0LTfAd7ywbIDc0F3tCrsOJKzbTsXLXyQDb1BIg==,iv:XRbngcWmMRollhHHWYcQhjtEUyvbNn23KgHS4HX1I8s=,tag:MFlcjFa4SSG6tIorglvtLw==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:ZZLiPiUU3P5vVxTnyQZTGlExDFlBowC2jI3/aRAwlFofbSD3QpThBE+pFnzqcOxWV/qRqg2oswxl0C2UqwrycCs+xTnyE7AvNFNWU27A0+KmrQbmY8Q7,iv:WLSqZ+JTygNznnui3TUKPbaMMfq+F2S8tmBZp7CS/K4=,tag:uEICEuDuFX7mokNUx3mA/g==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:3cLJHdS5GbAH2MqlHGvIxeoi,iv:79pYOis0qt5jX7FPRsNYZu1Q4yDMj7W9UGkxL82Blrk=,tag:ygCa6PZph6QRNQBEt8REJw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:3fjME6yPDS65Mhyn9hGwDj6v1nTOxVOoCT/B/FhVSngsQ2+sUK3Wg5B55tSIjuC/,iv:McFpeOqmiwDqbjUlG8YFfDe8e2SxZuEnoQn9s9qf3CA=,tag:U18QBGlEuxsaI3ln2vJRxA==,type:str]
    MAILER_FROM_ADDRESS: ENC[AES256_GCM,data:SMocSRI/LG0ANIIMw5/tJfzZ,iv:KWRSSD0ohIS1icw2cfBtjRZ58QBodsAVhQCcxzYzWow=,tag:M2TWX7694I5N/R5RK7hEMQ==,type:str]
    SMTP_ADDRESS: ENC[AES256_GCM,data:LUdZelNM6w65blsViSVL334v,iv:vqDNBFwmMXMD5pUr9p7QCOrbQ4AN2pRGAhbSqv/c5Qk=,tag:q0huaD/xPxBoGdj6X3u8dw==,type:str]
    SMTP_DOMAIN: ENC[AES256_GCM,data:lL8lrT/ysFb3uUk8V+5SFKuHi2ebgoWXOK8=,iv:m2QZ+sRiaFRmbojATqB41uT1rFsVYClXs9WV15kDRy4=,tag:5tlOkmCHzo9rTeZqob3t7g==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:JVz+,iv:3S1VM35xQ2BMCx0CWdkhFG1gyGqzNSFxamYVfEK/Oj8=,tag:LfxSAZvKPKxVFHAloU8Thg==,type:int]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVFg1YjBaN1l2UEFxUUNF
            RHYvSnlzUHd2bE8yYWJrVGxZMzFKZ3o2NkFZCmk0SVdtbE00ZCtzTHJPV0FBUm1P
            T2dieEs2OFhMSTdaa2JPdnZwVGpjVkkKLS0tIDNVZmp5VG5uWUJ1dnBiYUVQMTVS
            L2RrR1ZFZEhYV1R6dlpzRHQ1LzVzdDgKemOVZjxfHPLPs0PMWcCbwQFuW9xOw2nl
            VWprKw3WUoKudHiQThHG8aO8QWAJ5U9HvsTV9dhPBZyFsiwcmm0cPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T17:32:34Z"
    mac: ENC[AES256_GCM,data:nB63LSZjqq1HMdBXYbyua0vAESuORUg4o91AuHf+qjEMjx0cHD4MuiIGMX9gsh9dq+iYsEHt0NTOAsuU9QJd5z8VXpcfivcRIWB37oTf1lMgH1HQsqJmM2Tgh4uqgL22IIN0GjojbLHTW05G57pmh5od0Hr/wjhRnIBTOEkpWQc=,iv:60ZmzypQi0zo4EYH82vtGoVzWP7Grf429TQrK2wwRaI=,tag:SpO7xyKwsdL8SYzVoHupdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
