apiVersion: v1
kind: Secret
metadata:
    name: fizzy-secrets
    namespace: tools
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:IWClSG6Elnnhb9ZdH+TjIbedM9cX9hckWmxK3GBJMz8Z+/iyaPFjw/vk7CNoRRzbak6Xam6rn13fgeLpni/GEjqU5H1B+fWiHMyrJ0iX3mGQXNudLnHawRABTtmAczpdFN+5yKVdwa/WxOZSCTjC,iv:mfWQ5acyR5zcZEvQqLw9OHnr7L6mjyGWWlRtZCMKvio=,tag:ql5elA1DZgX3q5mJsGKT4g==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:qY1oU3V/3VPCGYhM+qFeJlEyo4Ttg7RERZjyeB9708qF62zJ7Mo9JHteqw==,iv:ZCka6vJwwQUhJgNEnMmCIWZGN9Hh7VayKazfOeEZdaw=,tag:Yyloll5I7cIaE6wAjnOLuQ==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:D/i4rLlEYsyfkz0NqJY61rmvJD5f/OFTP+uurozWrWxXXfBtI2kc5pYmjganAk7hyXtgNsuLEQaSixZ5pXmDBVwigxEQRqVHq6jihmuuf6xGw82s0zeQ,iv:I90hCzB0ONqfnT0C8M33PZg1W0TVIjn43ixKTGvvhwo=,tag:zNpgvIQzEtJnu9kxpTpWDA==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:MQkL/ZpVNTnzCHyTVV+xYx4d,iv:WlDXcIhmRYr7Y+QDUBPzYgfc86tYa9lvMX7tfoaOLJg=,tag:cTRZGTAg38kfX5I0jnOuxQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:zhxjM6TaHKrUJLnw1N08Et58Xh0uhTyrddOtCXGPlA5uy1JCOo1v1DRCte/Cw0Xs,iv:z+iqtJbkoaR//3X6dXhUOt+ueQxCJDbh1tI8COjW6sc=,tag:misi8SAkVd6pL3KO0nOe5A==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Ny9pME02blE3N0ZLMjNi
            T2xGTW5IZ0JQVEQ3b1NhdC9Ea3Y0aElXNUEwCnE0SWM0dlRjWm1iSURxS1g0OTJ4
            eDZUR3ZBc05lNFRKRXkzeXBMRFlITjgKLS0tIDhZa09nYitVUEZtelA4ZDVJVXFE
            d1VZN2hNK0NTNnNyNW9oS0NvQkg0ZW8KX4hc74FfSLtb88aATZxNsOcwBfeMePJz
            qnq8BOjC8t2QPwGhbkQp/v6YaqxMTn+AJFSIzJFqd1Ir3scaBtYgnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T16:22:27Z"
    mac: ENC[AES256_GCM,data:pBMoIRRcuNztKpc8yafzmQ1WlA9+X1QyRz8XclbhHKAjbZPw9+xSyXJ5njXfsr1Lm0Wxfyp4twOi/BGfTvkWMFuIJ4Pi2s5miPaK9otc7vmI87HzDV7mB5k/l7mGMtDcNDpjizx1BaJoA6OdvuG8a8t7aLDFLo4CLqu9EgZLZXI=,iv:FaATY36TRVFDaqkb1tfzGTyFW9q/0n7ARbMV3z81bs4=,tag:wC3zGD4T2t490z7mWyaXSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
