apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: null
    name: flux-image-update-registry-auth
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:2meMduuvY8G6+36wJZiNGSEgpcur6QCmsVID00kQ8lLMirGfc8JP9rJfFx+baLg1b8LtkTavA3p2RLhegfDMOwCWUrkZ7o7Y1EZT2SABXKTvwKNB70Q6SdrgfrTx+bRP7KeL397xR0pvkfExrVFE/AWu+y995ZymLUokrJV7VibBJAzasggfIaX5GtDHAGP4lYG/HaEFzgSylWTnMTcLmX1JEX0znecNFWqhTTLPChYLo6wJpnLr8LXVgksUr/vdTprb06ZiBX0=,iv:hsiyX01mcoyY6sTqJEpubqodTTBH2gVQBLBpkNSoxoU=,tag:blnVUk1Bc+eS9Nbrpwc/eg==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxM0xVSHRjU3VrakEzZ002
            TnJQdzhLaEduRDg0Q2ZSMlFpWTcwWGJrcmlzCmxhTGI2amVVdmVZQlhuY3JnLzJT
            SWZWdjR6bER3empRYmpMRjVqTzM2VGsKLS0tIDhuS2QxTDdzRzNJeElHb3VqN2tQ
            Z29la0JNcHkxcW41N1pMUGNKQk1IMmsKn3i2kUcDMyihAFUVUZxT+rTOmqSpZBLV
            93Q83rYwg3To6SXSiJqAjDGG+BGNhgzdamVDhj/6jXEtAiyOCErV7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T17:05:29Z"
    mac: ENC[AES256_GCM,data:nkJDo5Kgd23MWvNFeAzweKQoegixzaJnZD5cH0vtvean3zt8h6MTSZWaU7bH7sEsRUiUvsnt7JyD3bZ0wFbpSbwduTCyLGcn+9m4JmLCCOmzzjSmH0e/iScz9O/r3laIXAnN0rNMDDXE6IkojAaWxZZe2tAUJVx05eWnAiPu70s=,iv:cCRdd9Wei9Vt4Z/IP50y4dvwR9kr66sEl5YrqPU7AYI=,tag:dFFOQhGkwO6bzc2JVnfnyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
