apiVersion: v1
kind: Secret
metadata:
    name: s3-garage-access
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:POmWJ/7erhkhcOKJukPT/edsQE+Jy0MBdrQ=,iv:L2j2UftEEdY7lLhcy0V92ywXqmhgeChyPRt75C6PgQE=,tag:t5nvZN8cyLF8q1fo3hNVPQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZP2CJQoPTYMeTqrPe5csBFGaz9z69YWkRpql4YO/tabWKraaDekwdvb8qH1+DML6/BPjzwbUAFU/gszAb77wSA==,iv:HAosMGBHOvQBQbbXXmpvLW7BE1je3xkKa8i7PuBI8IQ=,tag:JdVw1/nZwyj07m8Ck1huQw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:2DXCuptD/XC4CVhG+ZTKKpMW9T82O+z4mkDeITaVBghxWc6QWcYW,iv:KBeMZWxdhFX4XbACQMq9PPtFJJY/sglRvjjfnyksGRg=,tag:ttw0R91v8daX0p+MN/DXaA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:gr52Fe8y,iv:MzPiNWpC4KhC/Q8D0ko0vcyi/iqOF2wsycFkpJtGev8=,tag:LHhnOkslRDATNPHtRGmtJw==,type:str]
    VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:DTbYtRo=,iv:j6wjbUN1p33K9wEEGZ6TI6IamWZyCwMxdEqZjI/4g8s=,tag:9OBAHABoMfIdh1yiL0s25A==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETjBpRHNUNEI0MVd1TzB6
            UzhUa05zSnB4OWM0dWJXVU9sUjNYdHh6amhjCmFhblpYOXZUcnVjclJqQWJ4cnJZ
            dXhLMVpWbGZNRUtkdVF3cHdydHJCQkkKLS0tIEsvNm9GVHNrL0hxUlAvL1dUb2I3
            UlFORVdaQnBSVjlzUCtNK04xbHArT2cK/WRQ00ePGW9zFT2vCSEjDhlrAi0ZKtSv
            HW6w0XhMUUzsOq47mthFRc1/dyhHj8f1slDOXChCc/FZHn4+YMoXxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T17:06:23Z"
    mac: ENC[AES256_GCM,data:775etJXSaz0RoKqnYj4p+6ZrFRuhQ6tiUvkD6lVLla3Xfq9BXZPNhVNpXfxLpBBK0kc83QGV8nFDRF5BUIz4nPD2hb2x2kzvBjw+nbTxQWF2DgBL1eHZHmw54anmYebEQ13LwJus908tZJLf8O4s3TFZ15HM6X+zwY6fcXDqU7g=,iv:kMO7GPI89xzA6frQh4AunjhQHKUwBKebv1ZoxdJJYf4=,tag:hgPGfjmezDApQkmL8b7scg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
