apiVersion: v1
kind: Secret
metadata:
    name: s3-garage-access
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:2Y4KnwG7U+eVWj/IWrJQUNHoEDnxdAma9EI=,iv:lSyElU8zES9Up2Exgrwrd9R8gRavVEU+e04lHkXKdSo=,tag:QA1Z5CoOAwUOLQUS6y2oiA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dBjy1NHaBhmMF9dnFaHtU0Sl3o4rJycS40jhq4ZLbn8/g89PuCI3uhBbDM/1JAySiES/YoP82gpvkUczuhUomQ==,iv:lR63VhQKY97/oJG8ZSB5lQnuMLm5SjEngJhUf4Mu/gc=,tag:djtV2is+C02OA5jylfoStQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:zbNh81t153BxMd3HWBkiWPkOTPjhpowS184NBchoCihX3qfiOmoz,iv:/gEVzVqbyumQRyTPLaOkDD7GNsjyLUXzK1z0OtRp+2s=,tag:hpE5uwtyeQMmbFYZ4ULzew==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:G8e8tyqZ,iv:GZ9BJGZe+Y8GLrBxx3iWOJ19ZM1VxPHE7WVByGjdYtU=,tag:dRmRDi6yECJsNphsiyscTQ==,type:str]
    VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:ISBkgjM=,iv:9EIpnTge3rLtWD+pdssxtdDYdOphxCy1UjYRIgquhPo=,tag:DSjD/hNPogrKO6xXTn1keA==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYkovUm4xWXc1NmJTNFFQ
            QnhSdHBMR2xYZElUUEphTjRwOTJtUlJCMTNBCkhjcnNFdHVWd0FDZElndVgvN3Nj
            YmhIbVNpNVdvcERSOWpYMzJQZFlhWjQKLS0tIGlSSlhXV24vcnN1U25ldEtYeDhi
            NGQ0cVB5ZmpPWC9ZZlRNV2k3MFR5dlUKf8K06vjqy5BHnYjaw7wW6B3MVKf344gW
            rh4qYXMldFRPSeayCpl5xIkfDsQemp29FUd1r/jcIme/9ky+JgtLjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T21:29:59Z"
    mac: ENC[AES256_GCM,data:8jTVL8sNHYHAdx1BynPPI9Xtc8R3DRmjDeq7hHGi4eMQKT5No50oX2/C6C1tjDu955KX6rWy3uNAhKvfdnpED+Djr2wiKvfhbthU3vYbAWDuh03ON9RIvCLz5Es4az6dyfcV8+g9SCNlDAz9/oivShshY5RSwmwARsEq9ZmGtZU=,iv:jzV7uldykunbTXS7qPDt1NT6ON5dtHj10b0YCvfIknI=,tag:O+Mm0QYtpFXbFT7vwnrNTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
