apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner
    namespace: gitlab
type: Opaque
stringData:
    runner-registration-token: ""
    runner-token: ENC[AES256_GCM,data:70LLr4xf83/5y4g9jIzh+c19QXKa/vreG8mc2zl9qyC7LtscihPrpcz82ql7y3Q/Fqk=,iv:FEifzJWttASuIMnKXneQMZrrDy5Cp+srmBRe+lJHQqA=,tag:zDrcLkoQa7NXmJuUBiCsNQ==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UGcwUStQQ1E0YXlhS2Rh
            c1JEaG1lVlNxM1BYcnR1YlFqd2JBSE9VVmo4CmdkQnk2RHJLaFB5N1M3ZzZ3MWhM
            RGJSeEdOWldpSjVTYWhqckJaaHhwa28KLS0tIHRGVFo5dGpLMEVUZlVEUml3Z01S
            ZU1BckJFYVV4c0RmWkdvQXBSbUZ1RWsKhIsXZL9RUt6rGkT0QyXVEy+ryrQ3wjGQ
            IhKZJZ1tRPExMBy1C7G7dND1eiucehu26imp0MFusOJB+jyWo2rLhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T17:46:00Z"
    mac: ENC[AES256_GCM,data:VHt/idg2LfPAjo/4CA3BnqUqEAc1op5jsnSTex1jPrvqv9Iia1o8t4JDhoLs8Q8rBH5scLahJdsUPjiNFBq7O/X1rV+qIOlqWFLCvoQEspavC9GSzI1vT/Z/WnSQJpQlVR6dnyoOHZzdu599ouxoz2WvSq8z+2L/1PAW80zlxTw=,iv:6y8mKZoRKNtM0xM0ho+XUa0n86fZ/+4gKQU5ikcGPhU=,tag:43cgo05jPOjwcAkIDTg3xA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
