apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: tools
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:NudDgjc=,iv:2fMLjhD8jPR5HHzZWflaT8j6FFYFLQL/4onFNHa6CNk=,tag:Ih+zPkPmHiJH9jpj7vlGtw==,type:str]
    admin-password: ENC[AES256_GCM,data:tcHrVpOo54WhpKm7EmpJb4tCGqn6r0W+YkRZlKkPHLsg2B2yH0AcQoQFPP0RYy+9VbsFJnqf3h2VXBSTCu3NT/HbWSDAfY6uc/tnPOCw7m1BGQJ1cjyfR1LaIb5msPfe1+qCdkRBeHDfjKG/OsjMJN5P3qt/d2moy1Bs,iv:lPEWAARhu3pprR4FiUVXiZAlftiTYqMxJbfJ9hCPATM=,tag:vZDPOVqQsuwSPVfLg7OBPA==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cDdROURiMno0aEl6aEEr
            alo3L1djSDROMlRQZE42Wk56RTY4UXJScUE4CjNIR0R2RnZQSm51a29ua0s5QzNR
            SGdSSkRtdWRHSlBKd2tWK2xmQWlwMm8KLS0tIGpKOXM1bmxpUWd6VUJEeGpFb1JH
            QjhXcVpjWENBVjVxUG5uTWFpQ1E3MEkKj8dtF4Kjux7QlugSDyUlxB6sUUs1MBT5
            BVwBCNbX7KyTAQ1Zioe/Y9zxXNmfxfuIMXZOP1h9VKrwBbPeKPL0Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T22:16:09Z"
    mac: ENC[AES256_GCM,data:vlMNmT2WARqfamHIWsf0iKEtUbbscIUkLKiOnT2YGe66eYTRs8ee+svgAoR+EMiWHsAkEA4GFcIfkNW8mK5AmmuQCPAF9OgAV/S3ciz61hS7+tdmD9zzZGRpdr0++jqKzsQB9tMuJFc/hJNs1EjwjDvQvzMeXYv+HdcwMR3rEa0=,iv:vPveia6nfd+vZqhilTBW4QMnAPlB53qQXnhFLfo/ctw=,tag:UQ3MJX/Xe2NU7xFT4NgABQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
