apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: victoria-metrics
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:vuH3g0Y=,iv:Il45us0KDZogrRI7M1WatB4wHOU13KbfFRDUGtjMue4=,tag:jhRmeIDiNegmIc2ipPMMwg==,type:str]
    admin-password: ENC[AES256_GCM,data:R5onyLBriGQfpJ43658o9qA7CQNu94UqmWp7IH0GSCTzrgwrxPxunD5ZOBFVjkZrzBkkUHXXQnHXiD9GTAgqEN1htnTUVEN2NBOPSbo8RQI6RZ+qMZnyGpEHHl6ID/HOCLsrkaLHA+Z8b2+yEYXlo0uwR7Khgq/T36xQ,iv:537ZMC3KL010caUmk2kT8YTIcy3RxoPFdU+Onh7WAEI=,tag:DAwurv9PYORQCKaY48JZAg==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZ2ZjWG1KUS9TQkFlZ0hw
            cHl2anU1SzBNenN3S0p3YndPUHZrV3RCYWdZClBIWmhBelRVbFQveFU1eTloelBN
            b0FlL3R3cmNMTDVSbHIzcENId1JKdlkKLS0tIFpETm5ma0t5QmYvcFJZR29QSVkx
            RS82MjJUcy9mV3hrcVE5cDhuTE5xTGsKYaF2zIs8h32CNsuoeYYOUvl2VSDf5XRS
            DXma+PTIQGPdBA0swzn7m6KLTRqFYEHgC26V7RhgDDkczfe003OOng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T18:26:18Z"
    mac: ENC[AES256_GCM,data:dc98cDRqtuRzSdi3dsczwn3852Ay+ADvSO3qLSwFXxrp1+Aej5eX0hkfNqCzxBB8aD1JWlyLLHJrazC3ZYaP64NLctLff9aRv1HvpT36LGD74OzIzWS/64qKDqdjIpU0/3QWAij+0boJZHjQx0+GmqfzgkoFprRwB8Y8X0Po95Q=,iv:rMWaY9UyIZIgdhu71UEDNQ0pzliVXmii20TET+ULqr0=,tag:o2pP+aAkHB6qQ8IEdOTDYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
