apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: tools
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:ojY31PU=,iv:q7rQw4jniXXvKfW898njbb5oXugxLnw2WRK4bkyi2ZI=,tag:NehzQkMBfL53IlIdUpPa7Q==,type:str]
    admin-password: ENC[AES256_GCM,data:dejhFlNL/NaP2k9QuZnfy2gMHWm3IRJzX+WFc/jKGk+DpY32jYOHjwX9wt7bECxscN5sCSrTyxLZ0A1BT96go2p3vTRrJDa1xfZTb8ICka4XsKOxBaslThR5Eskpl6MAfiBdN5fm6zIHiojNkCIiw4BZeXVGxTRCDuf6,iv:s/MQxxUuY7FcCeTTD/28rTgMlVWLVni65OuWVqgoPn8=,tag:xYa7D3DqKoyKxKT4lJJIwQ==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvU0FLZjVjbE9FaEx3NEFF
            VHpITXpKSDVCZS8rbjE5d29CZGJqUW1hS0RRCi9kUU12dzZKeFFrTE8ycTZyV1E0
            MS9qZFhJb08yN0FvdnpLRDI2TDBhRGsKLS0tIFdCVTl0UUkvY09kRi9hci9ZWDFM
            RWxPSWlyWmlmNWN2NG9YSFlGdGVtQUUKZ8MeIWpsb78YDBo5eOvVy86ytI0N/PXW
            ya+fJ/uO74UQBD4qRgzhyJSL+yE/rgQlGwEJzS+qT/F0ubeyr64uLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T18:10:42Z"
    mac: ENC[AES256_GCM,data:lUrHkFJf9RBfhAQ3BbBb2V9KcmbgKkaWBLL3RlKXzEY2vlV9u5hznElLMhkY8kiL+78isWaSUHsbB6y6Ieoe+hvGorzrz2a1RfMeWQ2R3aJJ+MBCIsxU06cHYs/LVMDb6jEp9AO8uNKWTgUqDE/kydtfDiFXdURV/Xb4jR34o1I=,iv:c2m+dF2/dtJ6sUQFwd2IpGq3lJIaEY3kEDC6pthxuUU=,tag:RnTWVpE7gAwHw7UdTDlCnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
