apiVersion: v1
kind: Secret
metadata:
    name: mailu-secrets
    namespace: mailu
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:rf0TrXIvHu6kSQJlBMvaxw==,iv:el5L1bNCqsMQCDHSwvw1V1ANFXfGDJveO9J5Lmm7/WA=,tag:yuso89arpnD2gZ+f5Wov8A==,type:str]
    password: ENC[AES256_GCM,data:gNHz2Lq999hy3bQhqQQya7tydIp499lDydTRa6nWo0wVRspPTlc6xw59,iv:0WHNW0KaBNwWFJkuaRdQ95ixi5sMfoDU1ULUXlrHB28=,tag:e/76TxkH1Au/R3GWSphXQw==,type:str]
    admin-account-password: ENC[AES256_GCM,data:MC0kKM8Uelma3Suc3e0EMTN5Ol0Y1xIFJ9LTCv7ymIpxoT3TBbs7YgLqIw==,iv:tqz4iMr4JXZwwJFEiSGA1aBEfttmUm8AMRid/skmlks=,tag:WRVb5vjcX58buJQ8VLBttA==,type:str]
    postgres-user-password: ENC[AES256_GCM,data:2ZITmOejiLPnNMUwGqo8hJ1oFw9MGQoODFhhrWkT8NV/eIrbGGwlZMIL,iv:/APDzcELSwcSa7rv+ldtL0aLoDzNIseuLb6frnVT0UI=,tag:5ERrIE2Z5f43W/r5eGPSBw==,type:str]
    postgres-admin-password: ENC[AES256_GCM,data:ozXLSpPGH4/hfk4XJe5qWioE/g74DxagHeojoDrwPwixd6rsZE6Q,iv:2i8Lc2+0e7Xpw6HmhmZl/t9fv/ek00dARbc0FBvcj6o=,tag:KUWr/Nfid9O4iC0BMbtdCg==,type:str]
    postgres-replication-password: ENC[AES256_GCM,data:muQ7xhTM1Q1gXJSXWVVfjuT+oUYoTG/oOWQUjOfEt+/bUtDMo30Q,iv:v9D2Wt7yELa9pw/vlDhQV7yohwH2bTHdJbySGR+CJMw=,tag:AZ+2Kl0c0nmsFXMrXcD3yQ==,type:str]
    DEBUG: ENC[AES256_GCM,data:vR9BXQ==,iv:iH0cNcCSLdLEtB3rHm5h5zSptmLZi/rTWEVCTWWDHRE=,tag:9nB/YGGWnJH7n5glvFw/Kg==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdXFXRDFrRllDQXNwWXhJ
            aVFGZXMxWG5QeVFIekF3Tnd3MXR5Wmp3KzFJCndMeUpGaGI4TlFSL05HSDQxcjlQ
            bFcwcFU2WGVlNlRRQ3hrclFLay9vT1kKLS0tIHVUVDZPNWp2a3JvOVFvRWJrM216
            QnhobW5jSW1IYy9kR1duWWM2NW9FR1EKeP6t0EUDtfoyyl7iYza56N/zI6b7Y27H
            kyjlGWRI5UYVqt1ATJgb1p1XWSmp8pRAgd+rwfIRp+1qTjbxEemfwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T17:46:56Z"
    mac: ENC[AES256_GCM,data:6+fc4XvHdt9aMTQ6M71vnRKTGRUGN9ova9QIO4vjDdRZ+8MrtUnfM9lvW/rc7PcyNM50pU/wsvEGUuZWcuTyVP90nMgSwcR67Md/FT0jAsMfCETnmX0bV7KXYiMEt2o9xGO3GMcS9/8OBN0msnMpWKQwJWEnSaTrWo/NrYyyusA=,iv:ynowgyBvb5Pzkt2bgUbNxk6D/JR/sawSddjDPx5vUJU=,tag:9hwbP7P4o0IgXxl/DDGvZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
