apiVersion: v1
kind: Secret
metadata:
    name: discord-bot-minecraft-whitelister
    namespace: tools
stringData:
    DISCORD_OWNER_USER_ID: ENC[AES256_GCM,data:X6e5GKaePmg4CH8XhPDl7kf5,iv:cO29ak/1vHu9YVnXqjXc/g4/U4rBZtKx7BeO6K+2ygk=,tag:zITq1BjJMnUqmEbPTL+51Q==,type:str]
    DISCORD_GUILD_ID: ENC[AES256_GCM,data:aeUKoGCWM0vfnFV2HXFygofn,iv:nq8CIP1b0y1MNtnJ8k5iqiUZMBkizs8yGEikR+9CaQ0=,tag:tzkX5+kw8mieU69jDtTRmQ==,type:str]
    DISCORD_ROLE_USER_ID: ENC[AES256_GCM,data:Yp1Qi0vtbVdJdJPkEXsoAtJyyQ==,iv:dI30fFRD1VsfA/vqg9XoRSMIY8u9KIdPRM4+avQAr9o=,tag:54s3fetBDGvs/nopqwXQFg==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:JsxUmeG/KgF0zy/vF7mVxrt2IoqKu8WUnLcEA6o6H9cGJyY98PBHTxjl3499NpW7Gxr3+/6PNB/cP23wXzUz5XlwmPkJvrEl,iv:Cn08DdQR7n56ECOlyl4WqUCFDJ1Vqfe/l+hDf6wC9jQ=,tag:ttdfgOs6IfiUJ7pn+Z+x6A==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMGJvSEpGT2JQb2RROEhQ
            SC90ZjQ4alhDSUUwRGRPM3liL3RrbmVVcm5JClI5Y2tSZlJQMDgzM3VKd25mWGk1
            aUNWcU5KeXZzcHZCSzlKaWtkZmRKMWMKLS0tIG01V2dsRVVaT1RRZ2IxOFRxR0dE
            Y21TQ3JlZGNoaThyQm1FWlNKZWNncW8KHdAC5MD0SkmXIoChmFilrn9HWfLFYz+a
            GtCXHG25J/tpo+xnmgkhwbb97U8K5eAGQObFqOYJ02xbyDsrFumSRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T00:06:00Z"
    mac: ENC[AES256_GCM,data:Yz70GAoWje+C4++Z3vsM4sOe6WlA84bC418P1ZFnw56549/3q2U5bZjwasf94MVXSBRsB4LJg3c5JigqqSHW8+9tDnOO2AveH7ZaodlO7OYhiYCcjT4aAW+GaRYfVJEtF3A/CZHTtSaQGccKLCr4/btiUgv3fBHnY+fKMam7BXQ=,iv:WBnCof/7Tmo9M8+3saEfXQXugPuN9DKWb+yeHTF+AM8=,tag:QCCGPD6bPjAZAPa+PlRu+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
