apiVersion: v1
kind: Secret
metadata:
    name: discord-bot-minecraft-whitelister
    namespace: tools
stringData:
    DISCORD_OWNER_USER_ID: ENC[AES256_GCM,data:QTuglSr7ketjswYDBINrMjln,iv:ok6Y4VU/a4MBcrSQ41EX9LqP/Ss5tYtti8v49Ld4K5A=,tag:4nnGQk0T0Mqz3OOWqaIgNA==,type:str]
    DISCORD_GUILD_ID: ENC[AES256_GCM,data:BYOfDZrKVCdYKXx+F2c5dSFx,iv:uoRmw4mGxC/zqxw15th90Z0t74VfqRmg4i+vcOeTNMA=,tag:ps9vdwGK9uBGK0zOnaSyrw==,type:str]
    DISCORD_ROLE_USER_ID: ENC[AES256_GCM,data:/I1yZf+AE1K1CQ2Ai9S6RlhK0Q==,iv:hJZsIkgtOv6K29/vSqrgA9tyG3QRfB3Qf8u5Zpq7p6Y=,tag:24xjhlye9aWzepFlovjMrg==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:PWGEd3OOvKRm4Pcz24+51AKgtbwo5FME5O45Ctw74cQ=,iv:bAcwGg7yIePLN1fVmBVOT0ord0zKJ+4dPD2Kp/scZwQ=,tag:HCOgFeeWdIhLRoY0hPowsg==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UEM3cE42NUxWcUxuOFFB
            RzRCMFIyN3hXVy83RW9FTkVUZUIydmo3T1IwCm1yeE81Q284MnZnM3Zvbk1sZ2ND
            VXpEWFRiWHNrSW8xdWQxc215VDMrR0kKLS0tIE9wMkh0VExldUFZWUN0b2c0MUM0
            WkU0ZndzQkYraGZkZGtBNjF0dUpGUlUKphK50fOF5YfbVsxJW4C8CXFz1zrgs8NV
            Cp3S+yf3CfE7Fzrv8uWcuY21VN1xUbeQKrAw7Sh89ZCIr8Ihkd0nGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T23:57:00Z"
    mac: ENC[AES256_GCM,data:my3nJTW2La6E8oef0pF4gGjr8zVR8VA5bpbr28N2Uju0n8B98Hzbcw5ahSoQsr3rAtVV8IvG/Eo4Hvm+BzMbqqa2aVWVFhS9om9zfA/vKjq8F58ULkpWz9OkrPY/0pdWb/CMtVQjiBClyJ72rUUZ8VDOfX0r+WB21ZiE7x5z9Vg=,iv:uTmhc/E7EgFaqMlLH8xWuzyNbn0Qr1KmglM2k1GD6N4=,tag:Apqkr2akGjldtJKhQWW1/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
