apiVersion: v1
kind: Secret
metadata:
    name: discord-bot-minecraft-whitelister
    namespace: tools
stringData:
    DISCORD_OWNER_USER_ID: ENC[AES256_GCM,data:1/YujMkzH3pxw3ymLVCVWfcV,iv:QMteYsmSGfsBS2CS591aJz2MBtTQQTFukijCz9pdmd4=,tag:iibsYQOa9ZTlKNnPhr6ExA==,type:str]
    DISCORD_GUILD_ID: ENC[AES256_GCM,data:ieRUX/R0uk1rTvh8ly7eydB/,iv:EVklhn/cZes8JfqchGflO522TJe5CBYRQ/WtJKavEpY=,tag:X1DRmMNulJ6xGvOC9udQKA==,type:str]
    DISCORD_ROLE_USER_ID: ENC[AES256_GCM,data:QSMckte1rACai56MG38LqAocow==,iv:3ir6hK4v7wDNyZIrmaPhz43Zn+Al9wJopXsRa134Qyk=,tag:A9BO9P/umLXEoeSGCWkQtQ==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:Oh0ivtlEE8+vq3d3zMJ8bzmI5qvc2lye/xhQH7ZP2noNnPnpY3Fa+VVUhJ/ba7fBZUNmgVh0i1urz2LYgbR8fD10a+zokxjs,iv:TAEks5XozdU75xtBFZCzdlsLbMhFOj2kfOrDUPBipy4=,tag:IRaQEPSt6HznmlsjsoKw3Q==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseTU2aFpHMzhaaVBJUjFY
            OVgzOTJqUjV1MjFFc3gzbVQ2RmdhdE9OdDAwCll3WnEzSHo2N1FpRjBrT2tuV0l6
            NHd6STFheVVrZTl6ZEFMeGxEM3BSSG8KLS0tIDBZemVLYldXWXk3ZWw1TDRuS2wy
            dG5rb2w1Q3d1Q2VZSERLUVEwbjNwL3MK5WfSiYfVOeULGgDSm4Vmj8xfnrUrD+gI
            lLQJfh9KoVdyamh+k/Eh/a/cn5Y3wdrkv8fTMFyD7QlnQ1Hm3pO2TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T02:37:11Z"
    mac: ENC[AES256_GCM,data:BPlNB27S6QTgiw3On2xLWaK3o+crPqIj8ToMXsFCI3tJkkGWqjDcBdwOh8D3lP/kXTEIDyux7CdVGM2WhWsj5nikwNO93g4zxLMfN4mL5vD5QxDK04LK0Lxyd6EKdJcsvFKXDPvYrob6yWXE+PF+XmH1MN3FGJP/ydqs07Y4//M=,iv:7O0o8SbO29R2uYBfZHAC+017+R4qaw7H37/uYD4Alkg=,tag:8Wjbno7r1eLWHpvSDERvtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
