apiVersion: v1
kind: Secret
metadata:
    name: oidc-secret
    namespace: ksbh
type: Opaque
stringData:
    issuer_url: ENC[AES256_GCM,data:xWkt8pX869U2ckIfWTXYDj9BTigqMpspOeAPWFCq,iv:nqidA8scJ9cJOYV/SzxXCybmFtpS4KwEH7P0yfXNlEM=,tag:Dg06kBB+6VgwH074MikzCw==,type:str]
    client_id: ENC[AES256_GCM,data:UMpDwFYoH5oYsyDtlR1BPDXdDaERGHsV4GZqyZx9LR5nxUsha7/qQw==,iv:UOGaAnntPTWHxWhXpc8660S+4NiNHd804yAdAPR11ik=,tag:53/vYPqyEclpAidJNYoxOw==,type:str]
    client_secret: ENC[AES256_GCM,data:Kb4ZrVJ1quDTe8X7+wfEP7bpVzxh2moGfD4qFMZIQ0vbU5CXRljdAL8TVJY8DQuwX4Mv7Xls6DpataKwMjkFb4v4af4gmB85t+B1I3rbBvJRS5AE9iu6LDbEQd5s6L8REPJHnxZhTrpZ7E9kXfdiB65I0mQSyImm8wvnpVKm0zs=,iv:gKWOrvO72s8c6HTMO9dwVhxZICzXgZOQoPzU227STDc=,tag:f/4ZhjktJUbjcg4MtXxw6g==,type:str]
    session_ttl_seconds: ENC[AES256_GCM,data:jM06Cw==,iv:tcjxs4keQUvvUoao0n/U18B4vb/YbIwVsVUL2RwZQjo=,tag:r/qo1vXzR8bpUhFOsVMHyA==,type:str]
    enable_refresh: ENC[AES256_GCM,data:EOeCofA=,iv:EI24KsNGk8SslHGrtmgqKyxrOi+VHYgJtFzt7BSZc7U=,tag:aKeElcZiKvERZDCRlE6+fA==,type:str]
    modules_internal_path: ENC[AES256_GCM,data:x4R9CpPdluGjPdDOIJg7,iv:WqAV6eiqQewBDS9ic/53ZhS5EA2PymTz0PbjtFJ289Q=,tag:p3VXxnTpgF3QrYkKNBQF7Q==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2czBHeDhOK3MwUWpqZEQ5
            a0UzOVdSbm03ZVAxZWMwRVoreHpVcjNvMWpVCmU1a3JKUWRoUEVPRmxzT2x3TVNP
            YkxQZTdNbzEzd1BjNEt2UE9RdFFGUk0KLS0tIEZBU2FCU3dsK3VpU2JGb0l0NCtH
            NlBRVjVrR04zUDA0UzNQMVdvVHJsVWcKj4DfXLm4PFIKOd1hU9zfRgQ4jpd1Iq/0
            I4/RWD7Pp2DURmx0JclNSJTO6dWGbfjYdLa4vjlYoaNlmBmR1QXR4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T13:08:36Z"
    mac: ENC[AES256_GCM,data:NOyDbxt+oTePaeaf5qibeM3ma7WWqkjg+juM03TH2WvUqHjSccNG+h4OQOMFlBxPWYtMIZyOcO/11+r3JGWZxEq6ia8k92UHp66HmnFBd/HSS+wXzYJ5Vg5Nu3R8Hwrpm6mf40NtGoPfpHfYs8TvGUw7X1xy4QpYqNRl9R9p80A=,iv:H+8wHKG8tdWhg6zEe1Exl1W/8IZxwYvJ0kZyxZghkDM=,tag:CpXuATsjQiskJm+ZSUNAOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
