apiVersion: v1
kind: Secret
metadata:
    name: ovh-credentials
    namespace: cert-manager
stringData:
    OVH_CONSUMER_KEY: ENC[AES256_GCM,data:8P8dXO0sE9EKvXiWci+CPVPP22B8CUd0jOYrtEwKBuA=,iv:CG3YPn5tj5Ie5xfhS+AdD7S4y2hEmSY0CYzsuEL6Q1k=,tag:kJGsg1bGQvzF10ZXs+9TJQ==,type:str]
    OVH_APPLICATION_KEY: ENC[AES256_GCM,data:Viau/rqcakjOUsLLhmI5Jg==,iv:j98tiKRg9ZErniIuXDhRtDxADeTOb7zhrRcwlPkf59c=,tag:x1jRQ/ExmUbJAC71EHMphg==,type:str]
    OVH_APPLICATION_SECRET: ENC[AES256_GCM,data:9LnJXXUvsyjMR0Dr/tP8glnUUsK76DL6Galr2LbykAE=,iv:VjC6qwMz6opiUPa5qtpyV7w1CUcmkfK9vvR4DdBKvlc=,tag:1zSdKJ1LvIpPX7EKCMALYg==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQUxNMU9zdlJ4OUU1cHo4
            SzVvM2xXcjFJSnF3NE4zWFUzUEZVMmVQb1dzCjZZT2VTWFl4WkhsRU5PZmo4UThN
            R2pZbmRnN3lpTUtQL0NtbjVyUmJXaXcKLS0tIDNlTFo3L2VtQ3JaRHdMSHV6Vi9v
            RmJnZXRwZ1dnN0QraUs5Uy9hcTZVME0KBXSMSS3Um+vX22reyjQvXCqRWjp11PsG
            +o8ihaH03128ipI/YB4pYEWVu0R2N0GUxLnnUVWg8u9IjhA9pBPs4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T14:26:27Z"
    mac: ENC[AES256_GCM,data:FhVaJaYAJYwTfD+0Eq8m68h1BvnCus/oXDzOpFTdO0ENP5FTlCr2ywjiorugNRL6dxm+ZMtpJEfOBZxDOq6ciodpNnZEn/7vZ688EH4ogcsVnUEJ7oo68Yzz3S8/P+MMwYnCjFykjnPvKECOnOCtzdwQZrr3qut+b88XI9QeO8Y=,iv:mM/NNUSvo7KW+siaAUn0dwz/+xJfQ7ok8DZfZoZijnQ=,tag:CBle3MbWKPDvgqyBdOFlWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
