apiVersion: v1
kind: Secret
metadata:
    name: ovh-credentials
    namespace: cert-manager
stringData:
    OVH_CONSUMER_KEY: ENC[AES256_GCM,data:1RYkLBfKgTkHPA8L56jPhn8JrjdinxfZxscl07aONuA=,iv:0b7MTX9Kh0f3HZNVYd4+9aPrOvGkr+JsERtCtK9CdII=,tag:ydAcb4N8J6dZVQDtZeXZIg==,type:str]
    OVH_APPLICATION_KEY: ENC[AES256_GCM,data:JvAejVYBdegvpYAW1a2G1A==,iv:duNBSsRJAp5Jdl4lSWDU2sT8xQEmDSYVYWhT37zSKCc=,tag:JCupMNCLa4M+5FHatoEK5w==,type:str]
    OVH_APPLICATION_SECRET: ENC[AES256_GCM,data:AEnJrSMwJY3HuJf8cekkRSzPdaDBy4ybLK51T8VaZSw=,iv:vvBNMOqqI2oFTAWvrxDovHUn0tWpWYmi3vlyezqGF3o=,tag:KwiT1fOy3MyhBkVxuaxD2A==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESWtZU2ZXK1FmVk9vd21R
            TnN1cEcvTXlITEJ1R1FibnplWFBjNTV5ODJFCm9mOXhobG9vbXpuRWlKTm4yWHVZ
            ZnZpbUVFd2Y0RGs5TXRnSisyVi9jencKLS0tIDZVZzFjMXpyamRPVTZnb2gva0Q3
            b2c1SGJWOHRCZElMWG5RYldqUGVvU2cKJycc58CL1Eu1qSLJmnuW3LsrjWccQKhH
            ORdtCBsUbLfQwF4cgi8qWVZxSBvHFU9P764j/Uk83zKznPPot7PtDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T17:05:45Z"
    mac: ENC[AES256_GCM,data:aqrRYZ+5PBbcT80txKKcc6NwfGiCFuVQfAH6HPQsWMz6vDZ1WbBnWfPDB5hzXN0ufRbtj+ObBm/WHRvH/l9V3xRtMfaxc9YXni5dIKOJewlkyUVjwy05sBOHaxbC7xjy4Gs+eB+NLvv7eTcGnnWj/GQYt/aJoJ7NuP5c6HXL/lE=,iv:dbv7C3asM2mJEAx5CPytbKsG2a/XyLwyU5bUd7XI9hs=,tag:ajXPVGx/aIhmVX1/cPnX3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
