apiVersion: v1
kind: Secret
metadata:
    name: ovh-credentials
    namespace: cert-manager
stringData:
    OVH_CONSUMER_KEY: ENC[AES256_GCM,data:KqiXVCASFyLRVekhNUJFAi2y/7x0vhsBdAYe7YfUbOo=,iv:N22DiUWaO/xUo+47UG5O/W7WNk/bB0iq/xbQvVnEjIs=,tag:P9oqkYE6kJjbOVbSUKxQ3w==,type:str]
    OVH_APPLICATION_KEY: ENC[AES256_GCM,data:R9bynUvi/4XDaZaJx0RZug==,iv:9qNcBoImpKdDbz2jYnIXLQAeNS+Dv254Zz+xjdCop7o=,tag:/DEC3oZSAPYZQqm5hkwaHg==,type:str]
    OVH_APPLICATION_SECRET: ENC[AES256_GCM,data:+1oB5hwMr13oOagdIK1U5GIyMkmewbX+TXyA6PxFHD4=,iv:gTBtF7mPUxFLhsGjYrN4ft6O53dESz+cjsRGr4pQKag=,tag:b3TMcMMP0YHLo6FiCKEw5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENFNhRk93RzZUWVQ0Yi94
            aUQ2UWdkRTYvN0JXQ1JudzE1N2drT25MT0Q0CkhRcTdqRG93em9yZDBHZHg4NDJs
            UFRzVk9WWUpSTXNVN2JyeXJOREpoTzAKLS0tIGVYdXpkaVdXSEpBSlVSZ3B0WTJr
            UDYzSVZwYk0yOUU5ZHR0aFVIOEpoZEEKi75nGwfqpAHFPycphzKhRBaiqTGvs0Sn
            i72Z1sAsKZsWojTujBtcKcF4Nm5UWkftJa6N0iY/+zOFVaaYgnW8kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T12:07:20Z"
    mac: ENC[AES256_GCM,data:wOg0EFDdIKgHqefo/KJgUg2/7QSfHYQATm+FhXQqNSF6ACRI93JFRCuRoTJ3pWeMCiA0FiT8jrn/qBa83wLP1oCXCN+aMh/KB+FqpRGgYAkzrBMzsJ/naQXyfreX//83q8AxFH+iTakis6Ja7LqR7qXNfRTc315hL05k111kczY=,iv:kmN04Exgxs/FZjrlQAEWmx5tKlhYAyCZGZ/6xZdqjdw=,tag:ueH5wLJ11RHq1IuivdClBQ==,type:str]
    version: 3.13.1
