apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:ZRXwZ2QH0fpbUlIONPBlx8JWB53jKLJtKBA/LWBwnmZi1hwu4Fy9tCsFllKqwf/zSw==,iv:4jsG0LMX4kqfMcyCgDUs+onC926fq9+iQUYrNEYajJw=,tag:mVEav6ehLGG+8vPl5VQi/w==,type:str]
    username: ENC[AES256_GCM,data:qGtC01ZlGRGe,iv:WJ5fU7i3EHN/t2sYGroJAkyPKVpbjOLZmZ2umKPKsu0=,tag:TDc1WTufAOkSK3pDgH87TQ==,type:str]
kind: Secret
metadata:
    name: pgsql-authentik
    namespace: tools
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik,tools
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWU40cDhiZHNUaFVSOXI2
            NzdkNFU3d2dSNDkzZkhXdExzcmdIWmNLY2hNClJJVkx2SG1LNXd4THR4bXl4aGFi
            QUs5enpMdTdQYlpqYnZOQlpXT0Y3enMKLS0tIFpKaG5NeTVKa0NNTVdlbnpYb3BJ
            VVJpMFRDa0huVWtKamlOQU9TclhXa0kKfMorWcPF8PBFjXicJ7/6IqgNWKyUaEWY
            RME7BODtd0fsIiDBOt15HOwzne8mbJEd6PyJhqWP04R8XJd7B05SSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T20:55:54Z"
    mac: ENC[AES256_GCM,data:CpEZo3d57Ywxo57JcjroSFk8SqoGva/V+7JBR/7Sw6fLEoBh8GVbw0oo81X8ZEnVRwonL8nu56yi9A/ggn9f4xNBZi4i1ZA9I7vL/XSJq6aaIlneroXaWdU7FRdQkx+2lOc3o9XFvzQZQUFlg/oBN/pMLSxEO/ZpWRtsl9lpkvM=,iv:4TCEnKBbbaEekFkYwqxTQPCUex0g32QX4MSJsSCp8P8=,tag:u12wLjRd9D+Za7fe+yf4Yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:mguAUgYUbFASZ6aveAO2/Ro+bIltlhw+NNOG7Goz6ERLoEYxwvM4yebjeLfYzK9uJ7qdWi+i,iv:wIUa57ODJt/L18wYBx6QueAqgSZbVZ0luTYT/OxGSKk=,tag:KjFm6Q/s/jIMkTqK+9jvSg==,type:str]
    username: ENC[AES256_GCM,data:4WIPWGE=,iv:4j4wSM0bmLJD+g8AGVUf920bdndhF2nDZD3VlhcmFD8=,tag:cmfuhfjrL13F/jtRyLqSEQ==,type:str]
kind: Secret
metadata:
    name: pgsql-mailu
    namespace: tools
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: mailu,tools
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWU40cDhiZHNUaFVSOXI2
            NzdkNFU3d2dSNDkzZkhXdExzcmdIWmNLY2hNClJJVkx2SG1LNXd4THR4bXl4aGFi
            QUs5enpMdTdQYlpqYnZOQlpXT0Y3enMKLS0tIFpKaG5NeTVKa0NNTVdlbnpYb3BJ
            VVJpMFRDa0huVWtKamlOQU9TclhXa0kKfMorWcPF8PBFjXicJ7/6IqgNWKyUaEWY
            RME7BODtd0fsIiDBOt15HOwzne8mbJEd6PyJhqWP04R8XJd7B05SSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T20:55:54Z"
    mac: ENC[AES256_GCM,data:CpEZo3d57Ywxo57JcjroSFk8SqoGva/V+7JBR/7Sw6fLEoBh8GVbw0oo81X8ZEnVRwonL8nu56yi9A/ggn9f4xNBZi4i1ZA9I7vL/XSJq6aaIlneroXaWdU7FRdQkx+2lOc3o9XFvzQZQUFlg/oBN/pMLSxEO/ZpWRtsl9lpkvM=,iv:4TCEnKBbbaEekFkYwqxTQPCUex0g32QX4MSJsSCp8P8=,tag:u12wLjRd9D+Za7fe+yf4Yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:Nl6aXJjd1/3uacjB2YNK1Pzlq/xRJzyHpyutMGTocRuwKWutoZmpMca0kMyPUIw+91Pm1Q==,iv:Q+oF1LMpci830mvwnimGuqvPw1qsH8p9hezgjicNleI=,tag:/DNu698tMHo5btgvDRuLmQ==,type:str]
    username: ENC[AES256_GCM,data:AflBZokc,iv:DZjeVPK3UVf0C8ACL3U8nT+ec2GJxx4EmT62ffvAnnY=,tag:3VpQyDKh/qA24XDodZZJEg==,type:str]
kind: Secret
metadata:
    name: pgsql-gitlab
    namespace: tools
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: gitlab,tools
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWU40cDhiZHNUaFVSOXI2
            NzdkNFU3d2dSNDkzZkhXdExzcmdIWmNLY2hNClJJVkx2SG1LNXd4THR4bXl4aGFi
            QUs5enpMdTdQYlpqYnZOQlpXT0Y3enMKLS0tIFpKaG5NeTVKa0NNTVdlbnpYb3BJ
            VVJpMFRDa0huVWtKamlOQU9TclhXa0kKfMorWcPF8PBFjXicJ7/6IqgNWKyUaEWY
            RME7BODtd0fsIiDBOt15HOwzne8mbJEd6PyJhqWP04R8XJd7B05SSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T20:55:54Z"
    mac: ENC[AES256_GCM,data:CpEZo3d57Ywxo57JcjroSFk8SqoGva/V+7JBR/7Sw6fLEoBh8GVbw0oo81X8ZEnVRwonL8nu56yi9A/ggn9f4xNBZi4i1ZA9I7vL/XSJq6aaIlneroXaWdU7FRdQkx+2lOc3o9XFvzQZQUFlg/oBN/pMLSxEO/ZpWRtsl9lpkvM=,iv:4TCEnKBbbaEekFkYwqxTQPCUex0g32QX4MSJsSCp8P8=,tag:u12wLjRd9D+Za7fe+yf4Yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:9W6Ogl3v4Lpz0cRrD1+VPqhq7jibuIU/ARyIiFXBrUbQ66RuOmx9eceXOWhxhIM=,iv:/laZB6vOfKPafzHqGM7nei+8tPxNZJNID/PvVsp6WGY=,tag:wiInBnOU3Ws8P9VuiUFKqg==,type:str]
    username: ENC[AES256_GCM,data:hnTJlg==,iv:gbD6NV9fj5CukfS/KIBxvIEth62oZKpwo7NteUZTZt0=,tag:sUyKhgazxVm+01I9s1bEGA==,type:str]
kind: Secret
metadata:
    name: pgsql-kong
    namespace: tools
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: kong,tools
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWU40cDhiZHNUaFVSOXI2
            NzdkNFU3d2dSNDkzZkhXdExzcmdIWmNLY2hNClJJVkx2SG1LNXd4THR4bXl4aGFi
            QUs5enpMdTdQYlpqYnZOQlpXT0Y3enMKLS0tIFpKaG5NeTVKa0NNTVdlbnpYb3BJ
            VVJpMFRDa0huVWtKamlOQU9TclhXa0kKfMorWcPF8PBFjXicJ7/6IqgNWKyUaEWY
            RME7BODtd0fsIiDBOt15HOwzne8mbJEd6PyJhqWP04R8XJd7B05SSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T20:55:54Z"
    mac: ENC[AES256_GCM,data:CpEZo3d57Ywxo57JcjroSFk8SqoGva/V+7JBR/7Sw6fLEoBh8GVbw0oo81X8ZEnVRwonL8nu56yi9A/ggn9f4xNBZi4i1ZA9I7vL/XSJq6aaIlneroXaWdU7FRdQkx+2lOc3o9XFvzQZQUFlg/oBN/pMLSxEO/ZpWRtsl9lpkvM=,iv:4TCEnKBbbaEekFkYwqxTQPCUex0g32QX4MSJsSCp8P8=,tag:u12wLjRd9D+Za7fe+yf4Yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:zWiw0FjUW/YrFcIQjkJVEgvZ9AyqB6RYPEhfIk4LN139F6WhrZrCRn7ceVDpaLY=,iv:24oL1f6qjorTa2kZQPhWLtw+fDHZmE+1+pAEu+r4gEI=,tag:GfTisvWsFTcMCKsfX53dRg==,type:str]
    username: ENC[AES256_GCM,data:fluqSWA=,iv:SNE2ayyhUKbjeCJE5GVdPX8z2Ya8D8PP8MyiQgM6SCE=,tag:qTMafsGo+cJsgm0nzfMd3Q==,type:str]
kind: Secret
metadata:
    name: pgsql-superuser
    namespace: tools
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWU40cDhiZHNUaFVSOXI2
            NzdkNFU3d2dSNDkzZkhXdExzcmdIWmNLY2hNClJJVkx2SG1LNXd4THR4bXl4aGFi
            QUs5enpMdTdQYlpqYnZOQlpXT0Y3enMKLS0tIFpKaG5NeTVKa0NNTVdlbnpYb3BJ
            VVJpMFRDa0huVWtKamlOQU9TclhXa0kKfMorWcPF8PBFjXicJ7/6IqgNWKyUaEWY
            RME7BODtd0fsIiDBOt15HOwzne8mbJEd6PyJhqWP04R8XJd7B05SSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T20:55:54Z"
    mac: ENC[AES256_GCM,data:CpEZo3d57Ywxo57JcjroSFk8SqoGva/V+7JBR/7Sw6fLEoBh8GVbw0oo81X8ZEnVRwonL8nu56yi9A/ggn9f4xNBZi4i1ZA9I7vL/XSJq6aaIlneroXaWdU7FRdQkx+2lOc3o9XFvzQZQUFlg/oBN/pMLSxEO/ZpWRtsl9lpkvM=,iv:4TCEnKBbbaEekFkYwqxTQPCUex0g32QX4MSJsSCp8P8=,tag:u12wLjRd9D+Za7fe+yf4Yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
