apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:wk637ZCkI0k+W8GhWpipkPT1oC/2Wd7QHMERn4KSy9Vt/0XH2hoIxlRKMyv4dCKz2A==,iv:2yawJdNVB1TXNWDKK74pstTs+/wU7P6HyZAMJrVC6S0=,tag:ZBolh9S4ZINFOuDrDzsItw==,type:str]
    username: ENC[AES256_GCM,data:u+eFLUWidGcM,iv:Z8OObvHoJvmTsoiHPBprIg72FNIdEvmhemxu2KB9Css=,tag:UkXE0TtcFg+m90RZIQMHuw==,type:str]
kind: Secret
metadata:
    name: pgsql-authentik
    namespace: tools
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik,tools
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RWQ3T0RZQXdqck5MamxY
            UWpuUHFMOWp5Sld4SVNFeWRFZEZ0K2tNc1VBCmtNcG1SL21CU2gvaDRFeHZSTGps
            NldrVGgwRC81WVRxa3VwSUVHaEUzdjgKLS0tIHFzNnhMY0g2OEZUeG9ESUVBTmR4
            ejVIV3hYK0o3ZkhxNlR1OXFVSTRBY0kKhn4YSLWEPC8dLRAZwXz2RshbKeExrUzd
            ZP+SQyuIyhoLaxyOedVN3JKGgAv4+Lq2CxUSy+kpBi31nMPOuW5MWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T20:01:54Z"
    mac: ENC[AES256_GCM,data:gj0dw1RnpRag9rhHvpBPpCxs4u8w9U1SNLcbzLBuUsg/Z75+jDCxBrJlPImuc1ek9/nSxlt0weubHpgBwY1g8+fk14TPvinZD5qMN/72kTcU97wlQRr3UdsxVC29f2Ti0kHEh1zEQfaTZ7jtX8QXcTcUnWqJ5/tIngtnPKSzHVY=,iv:5ZcpswlcRKN25zHXUUKaCPSffbejt9ATNheE1gubXHY=,tag:LWiV75hv+FNZ+eMkT/FSeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:/+97DPz2UgNESfvEiwYkTjTEHG2vlmb+PPtc133yqVzxyVhMSrce1nKSHaaowu0s2WMfyHi9,iv:8gSb0jGP20+tP/FL2QRH4cV5rs7Pid9khMViS/dcn1o=,tag:f0Sgrm/lZWu1H3Ekr5KO5g==,type:str]
    username: ENC[AES256_GCM,data:0jsLfVk=,iv:ZddCV+ycxrgHSjJZVQeZsFEZE2pvarEIObpEbYz/6R8=,tag:ckPBqYpNMsAdQlyAp5wmsg==,type:str]
kind: Secret
metadata:
    name: pgsql-mailu
    namespace: tools
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: mailu,tools
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RWQ3T0RZQXdqck5MamxY
            UWpuUHFMOWp5Sld4SVNFeWRFZEZ0K2tNc1VBCmtNcG1SL21CU2gvaDRFeHZSTGps
            NldrVGgwRC81WVRxa3VwSUVHaEUzdjgKLS0tIHFzNnhMY0g2OEZUeG9ESUVBTmR4
            ejVIV3hYK0o3ZkhxNlR1OXFVSTRBY0kKhn4YSLWEPC8dLRAZwXz2RshbKeExrUzd
            ZP+SQyuIyhoLaxyOedVN3JKGgAv4+Lq2CxUSy+kpBi31nMPOuW5MWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T20:01:54Z"
    mac: ENC[AES256_GCM,data:gj0dw1RnpRag9rhHvpBPpCxs4u8w9U1SNLcbzLBuUsg/Z75+jDCxBrJlPImuc1ek9/nSxlt0weubHpgBwY1g8+fk14TPvinZD5qMN/72kTcU97wlQRr3UdsxVC29f2Ti0kHEh1zEQfaTZ7jtX8QXcTcUnWqJ5/tIngtnPKSzHVY=,iv:5ZcpswlcRKN25zHXUUKaCPSffbejt9ATNheE1gubXHY=,tag:LWiV75hv+FNZ+eMkT/FSeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:MyqsTCiiy/ePIM0PUKNUxvawpCpaDVHWVolxSmQVdKD5DfGNF/9MvxM4CIIH9x6qlGvClQ==,iv:VSISZQX4m/1Hp+zFLuEb3NZU2JVzbVjDWUZ0fzn6Puk=,tag:K8MQ64ct0AaYOP+YX+SZWA==,type:str]
    username: ENC[AES256_GCM,data:lL11dxoj,iv:9nvWhD4pcxt7mfcbOvbPY3hIGLGcNJK/FEE4OKts3DY=,tag:YBAaWep20f2Y1NUXbdqJ4Q==,type:str]
kind: Secret
metadata:
    name: pgsql-gitlab
    namespace: tools
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: gitlab,tools
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RWQ3T0RZQXdqck5MamxY
            UWpuUHFMOWp5Sld4SVNFeWRFZEZ0K2tNc1VBCmtNcG1SL21CU2gvaDRFeHZSTGps
            NldrVGgwRC81WVRxa3VwSUVHaEUzdjgKLS0tIHFzNnhMY0g2OEZUeG9ESUVBTmR4
            ejVIV3hYK0o3ZkhxNlR1OXFVSTRBY0kKhn4YSLWEPC8dLRAZwXz2RshbKeExrUzd
            ZP+SQyuIyhoLaxyOedVN3JKGgAv4+Lq2CxUSy+kpBi31nMPOuW5MWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T20:01:54Z"
    mac: ENC[AES256_GCM,data:gj0dw1RnpRag9rhHvpBPpCxs4u8w9U1SNLcbzLBuUsg/Z75+jDCxBrJlPImuc1ek9/nSxlt0weubHpgBwY1g8+fk14TPvinZD5qMN/72kTcU97wlQRr3UdsxVC29f2Ti0kHEh1zEQfaTZ7jtX8QXcTcUnWqJ5/tIngtnPKSzHVY=,iv:5ZcpswlcRKN25zHXUUKaCPSffbejt9ATNheE1gubXHY=,tag:LWiV75hv+FNZ+eMkT/FSeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:o+cK9GixxZ76SKoN8tJmqQRfcDkmOOWbZiPrkChYRP/B/P5G9iQQmAMKO5V9cCU=,iv:DJqrsI7E1IHNd9efFg/p/RN8aWxzLaDj7483rajhXfg=,tag:diqYIIDCGAnzUJR1ZRB25Q==,type:str]
    username: ENC[AES256_GCM,data:k2/E7w==,iv:UFphT8tEZ4LFQ6rInnSUYNZ9ss2xCrEX+AC/uQE0Amo=,tag:BsuV1mIeeTv3FGsWTIWq/A==,type:str]
kind: Secret
metadata:
    name: pgsql-kong
    namespace: tools
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: kong,tools
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RWQ3T0RZQXdqck5MamxY
            UWpuUHFMOWp5Sld4SVNFeWRFZEZ0K2tNc1VBCmtNcG1SL21CU2gvaDRFeHZSTGps
            NldrVGgwRC81WVRxa3VwSUVHaEUzdjgKLS0tIHFzNnhMY0g2OEZUeG9ESUVBTmR4
            ejVIV3hYK0o3ZkhxNlR1OXFVSTRBY0kKhn4YSLWEPC8dLRAZwXz2RshbKeExrUzd
            ZP+SQyuIyhoLaxyOedVN3JKGgAv4+Lq2CxUSy+kpBi31nMPOuW5MWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T20:01:54Z"
    mac: ENC[AES256_GCM,data:gj0dw1RnpRag9rhHvpBPpCxs4u8w9U1SNLcbzLBuUsg/Z75+jDCxBrJlPImuc1ek9/nSxlt0weubHpgBwY1g8+fk14TPvinZD5qMN/72kTcU97wlQRr3UdsxVC29f2Ti0kHEh1zEQfaTZ7jtX8QXcTcUnWqJ5/tIngtnPKSzHVY=,iv:5ZcpswlcRKN25zHXUUKaCPSffbejt9ATNheE1gubXHY=,tag:LWiV75hv+FNZ+eMkT/FSeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:nkaXQ7cYphhGNI18IO6yyuYCu+KiUtEBp+KCYNHYLaZe8LXuD0p3G9gSp7WjsO0=,iv:NJwJrZGBm8GjIb7HIIAYPHbZQcM3nvmDKN+Hxm9Flh8=,tag:CkeUWKzEiXXwKtvPdf1/4w==,type:str]
    username: ENC[AES256_GCM,data:0lbrsZY=,iv:BMImq/RD+N9QkQU2C9OBiiOdm9JAnen6CYfPsI+xlos=,tag:kLUC0pUi2hhcVe3ogp4STQ==,type:str]
kind: Secret
metadata:
    name: pgsql-superuser
    namespace: tools
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RWQ3T0RZQXdqck5MamxY
            UWpuUHFMOWp5Sld4SVNFeWRFZEZ0K2tNc1VBCmtNcG1SL21CU2gvaDRFeHZSTGps
            NldrVGgwRC81WVRxa3VwSUVHaEUzdjgKLS0tIHFzNnhMY0g2OEZUeG9ESUVBTmR4
            ejVIV3hYK0o3ZkhxNlR1OXFVSTRBY0kKhn4YSLWEPC8dLRAZwXz2RshbKeExrUzd
            ZP+SQyuIyhoLaxyOedVN3JKGgAv4+Lq2CxUSy+kpBi31nMPOuW5MWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T20:01:54Z"
    mac: ENC[AES256_GCM,data:gj0dw1RnpRag9rhHvpBPpCxs4u8w9U1SNLcbzLBuUsg/Z75+jDCxBrJlPImuc1ek9/nSxlt0weubHpgBwY1g8+fk14TPvinZD5qMN/72kTcU97wlQRr3UdsxVC29f2Ti0kHEh1zEQfaTZ7jtX8QXcTcUnWqJ5/tIngtnPKSzHVY=,iv:5ZcpswlcRKN25zHXUUKaCPSffbejt9ATNheE1gubXHY=,tag:LWiV75hv+FNZ+eMkT/FSeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
