apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:SvlqO5IPGqfc3sXvivtikNUZwmbxfak91KKcwaPN8hdYDIkhi2Gb52/F4eyiGZdu5g==,iv:y9WYiMpqAP7GY8vZpUKCaAvY/A6vlcaB2D/X0BL1PEA=,tag:aCeM3J8f6oCsNn5ys8J0Fw==,type:str]
    username: ENC[AES256_GCM,data:qlAesG7s5l4t,iv:/7a52sPXf0rSkq/SEbK7XtTyaIBkn7KaS287YY9M9kk=,tag:FBYM8E3aonb4S7m2GKic7g==,type:str]
kind: Secret
metadata:
    name: pgsql-authentik
    namespace: tools
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik,tools
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL0RLTGE5R2tTRFZDdzZz
            cHd6WXRaRDg0THU5dTZBRi82bU9YYjBqcTBRCmVuMVoyektrSUcySkJmOGNKUTJN
            MjJrTFZnL3RGZUxPdERYeDB5RnhDdGMKLS0tIGRBMDNxUGMvV1JoMGFIa2tFWWU2
            UmFYaXl3NEthb0xOWk1UYVdlVWFBRm8KW2DJQ/v5YGiuKMWtTp4yDjWZsW5cwOE8
            Fp6trnh5haJfMudHDFsKEYjsf2YG6bH8n2/g3dOqOLX2RUmy38ekIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T21:49:09Z"
    mac: ENC[AES256_GCM,data:cBuHi7ezf0FfKqAKeeECQJ9jKPTK5ULhkLL4IAvVDDpx3tb6QIZS+AEhCC2U21NHg5NlZpSXRQ80WN5DpS0Zz20IVIU6tX2bGvbo+4czRL3bBrcVnnZrfaybj3oKXIEUHQhjpqOyhBxfnqEZTva4QijPq9phH/XOsfnKe5zVNgw=,iv:iDKzksCF4FZFGyFf3dwRPYHHz+O91QRMtBXL3GEq+N0=,tag:rs06hXABRE55Q77518r7rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:wF4C0buvZ6UJir/4zRw7SwwtJ5TWhU8G8UGYhD0lIq1cWVOq09dZwjmM5NWNP3sdWl4sdAq5,iv:ZHOOB3fP+LrPz6Lkp74SOsvY40qHpHuJdq2YbGzuBQU=,tag:VlX5Aue/PQRi0OkjTR+miw==,type:str]
    username: ENC[AES256_GCM,data:1B7Ai+Y=,iv:ICUhtxRznLquus3qr5YKdCqdH/OqLmrP3/itW4Q+Bbc=,tag:+l9JsLfEaVklEeLGXtzC3A==,type:str]
    roundcube-db-password: ENC[AES256_GCM,data:XGtKZttyYIMmvIYLGF4QxxeOnElSocHjFiRJkNaQ/jhwwX0fL2ObQLw98zGdgNec7AjMKMr8,iv:nPF6CQ1fgWVCcow6afMOVKjgS9cIDvxRE6DYSQqsKrI=,tag:gN/e8T29gOLVKTyF3n54DQ==,type:str]
    roundcube-db-username: ENC[AES256_GCM,data:glfrNqM=,iv:VC1G0uMMdVcOIZ6m1yV2NLWkzvo+0tkH9ziLHSmS5lI=,tag:jlPY77nRW6zoRA9pVTDVHg==,type:str]
kind: Secret
metadata:
    name: pgsql-mailu
    namespace: tools
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: mailu,tools
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL0RLTGE5R2tTRFZDdzZz
            cHd6WXRaRDg0THU5dTZBRi82bU9YYjBqcTBRCmVuMVoyektrSUcySkJmOGNKUTJN
            MjJrTFZnL3RGZUxPdERYeDB5RnhDdGMKLS0tIGRBMDNxUGMvV1JoMGFIa2tFWWU2
            UmFYaXl3NEthb0xOWk1UYVdlVWFBRm8KW2DJQ/v5YGiuKMWtTp4yDjWZsW5cwOE8
            Fp6trnh5haJfMudHDFsKEYjsf2YG6bH8n2/g3dOqOLX2RUmy38ekIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T21:49:09Z"
    mac: ENC[AES256_GCM,data:cBuHi7ezf0FfKqAKeeECQJ9jKPTK5ULhkLL4IAvVDDpx3tb6QIZS+AEhCC2U21NHg5NlZpSXRQ80WN5DpS0Zz20IVIU6tX2bGvbo+4czRL3bBrcVnnZrfaybj3oKXIEUHQhjpqOyhBxfnqEZTva4QijPq9phH/XOsfnKe5zVNgw=,iv:iDKzksCF4FZFGyFf3dwRPYHHz+O91QRMtBXL3GEq+N0=,tag:rs06hXABRE55Q77518r7rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:fSx7g2pgw8U2Gxqsx9V6dDrU/A3WB2rO8ahzCBv1Ijw84sBul++tyT5sblRH4gm7WE2kug==,iv:ADn+4IqKDuX0RukQGYjGgzRuBDo9kbW8IPHO33lPfCQ=,tag:+VdMctfQ9OrzAOe88AXDzA==,type:str]
    username: ENC[AES256_GCM,data:IUbqYxg8,iv:q/WDXe6/2vTqCMQn82tXjeiEen7h4d9aU+cMu3tsT5w=,tag:3YpMu1m0pTlcHnshmOi7cA==,type:str]
kind: Secret
metadata:
    name: pgsql-gitlab
    namespace: tools
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: gitlab,tools
type: Opaque
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL0RLTGE5R2tTRFZDdzZz
            cHd6WXRaRDg0THU5dTZBRi82bU9YYjBqcTBRCmVuMVoyektrSUcySkJmOGNKUTJN
            MjJrTFZnL3RGZUxPdERYeDB5RnhDdGMKLS0tIGRBMDNxUGMvV1JoMGFIa2tFWWU2
            UmFYaXl3NEthb0xOWk1UYVdlVWFBRm8KW2DJQ/v5YGiuKMWtTp4yDjWZsW5cwOE8
            Fp6trnh5haJfMudHDFsKEYjsf2YG6bH8n2/g3dOqOLX2RUmy38ekIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T21:49:09Z"
    mac: ENC[AES256_GCM,data:cBuHi7ezf0FfKqAKeeECQJ9jKPTK5ULhkLL4IAvVDDpx3tb6QIZS+AEhCC2U21NHg5NlZpSXRQ80WN5DpS0Zz20IVIU6tX2bGvbo+4czRL3bBrcVnnZrfaybj3oKXIEUHQhjpqOyhBxfnqEZTva4QijPq9phH/XOsfnKe5zVNgw=,iv:iDKzksCF4FZFGyFf3dwRPYHHz+O91QRMtBXL3GEq+N0=,tag:rs06hXABRE55Q77518r7rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:lDAxpmv69EqWu3U/Aa55zVbtu84r/8edfZyRsuzgGsSWN8rBo0hFN843HdUZe4g=,iv:2DqqN8NI2sNPBAtFK0GarVEfkE1ikEty6j6i+9AkXnc=,tag:G0ym0kAJIeL5/XmPEHVxdQ==,type:str]
    username: ENC[AES256_GCM,data:4F4W0g==,iv:XsKcD2fSzGXPFPfbplf1fx48Z7TTHT9GFUcX98k20+Y=,tag:Uegr609CZAVsU8XQXysFHg==,type:str]
kind: Secret
metadata:
    name: pgsql-kong
    namespace: tools
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: kong,tools
type: Opaque
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL0RLTGE5R2tTRFZDdzZz
            cHd6WXRaRDg0THU5dTZBRi82bU9YYjBqcTBRCmVuMVoyektrSUcySkJmOGNKUTJN
            MjJrTFZnL3RGZUxPdERYeDB5RnhDdGMKLS0tIGRBMDNxUGMvV1JoMGFIa2tFWWU2
            UmFYaXl3NEthb0xOWk1UYVdlVWFBRm8KW2DJQ/v5YGiuKMWtTp4yDjWZsW5cwOE8
            Fp6trnh5haJfMudHDFsKEYjsf2YG6bH8n2/g3dOqOLX2RUmy38ekIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T21:49:09Z"
    mac: ENC[AES256_GCM,data:cBuHi7ezf0FfKqAKeeECQJ9jKPTK5ULhkLL4IAvVDDpx3tb6QIZS+AEhCC2U21NHg5NlZpSXRQ80WN5DpS0Zz20IVIU6tX2bGvbo+4czRL3bBrcVnnZrfaybj3oKXIEUHQhjpqOyhBxfnqEZTva4QijPq9phH/XOsfnKe5zVNgw=,iv:iDKzksCF4FZFGyFf3dwRPYHHz+O91QRMtBXL3GEq+N0=,tag:rs06hXABRE55Q77518r7rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:8+5o8Jrit9WRawOMupjb87DvcTMm1KtTjo2E/RlWXeius/FLT2xHoxjItQ98heM=,iv:Pj41j+GeYi5XGym3ojT4Y/hoRAzPmzxOYbDsQJh9pf4=,tag:oC8w2KCtyQp1Ezoc1QRB3g==,type:str]
    username: ENC[AES256_GCM,data:lpRaiMcP2MU=,iv:qLnTvbPlL7FRFUef/+zaxgmnXJj6ZaY9tl5gDrIsGcA=,tag:p5GgVQ499JOXeW3BLUB9SA==,type:str]
kind: Secret
metadata:
    name: pgsql-superuser
    namespace: tools
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL0RLTGE5R2tTRFZDdzZz
            cHd6WXRaRDg0THU5dTZBRi82bU9YYjBqcTBRCmVuMVoyektrSUcySkJmOGNKUTJN
            MjJrTFZnL3RGZUxPdERYeDB5RnhDdGMKLS0tIGRBMDNxUGMvV1JoMGFIa2tFWWU2
            UmFYaXl3NEthb0xOWk1UYVdlVWFBRm8KW2DJQ/v5YGiuKMWtTp4yDjWZsW5cwOE8
            Fp6trnh5haJfMudHDFsKEYjsf2YG6bH8n2/g3dOqOLX2RUmy38ekIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T21:49:09Z"
    mac: ENC[AES256_GCM,data:cBuHi7ezf0FfKqAKeeECQJ9jKPTK5ULhkLL4IAvVDDpx3tb6QIZS+AEhCC2U21NHg5NlZpSXRQ80WN5DpS0Zz20IVIU6tX2bGvbo+4czRL3bBrcVnnZrfaybj3oKXIEUHQhjpqOyhBxfnqEZTva4QijPq9phH/XOsfnKe5zVNgw=,iv:iDKzksCF4FZFGyFf3dwRPYHHz+O91QRMtBXL3GEq+N0=,tag:rs06hXABRE55Q77518r7rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
