apiVersion: v1
kind: Secret
metadata:
    name: pow-secret
    namespace: ksbh
stringData:
    difficulty: ENC[AES256_GCM,data:HA==,iv:NGKZbJqXfk1vaMlWJYu1rvkv30Q3333/Gml4jf2NDvU=,tag:5YrWoeosImpu3Rt+yOp3Qw==,type:str]
    secret: ENC[AES256_GCM,data:U+j/6LdEysDxqhuSR/iRoX0izF26hSenyFrHhcPeMqnGVemZqOKNVj1ySn8FtJiyViLRchc7BITa76jdW8HQBg==,iv:d8nE/NKWehRhJsMU+Q7i/2cdC1+OGi4lTRfMRm9Zmw4=,tag:CrBktzGQ1pwhXEZp1DW6VQ==,type:str]
sops:
    age:
        - recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweXY3N2l5L1JvNlV1Z24w
            cldSakk3R0ozNmUyUk9uVS9GZnd2WHJUWkU0CjB5bUo3bWdIZWRrTm9xQWpqRWxY
            L2VzVisrYmJxdE1CNy9WUGhNQjNSQTAKLS0tIFhBT0VZQkcyT01HOWFpU21sSlVr
            SWlhZ0RCT1hnUlFES3kyVHAzOXdDaWcKfw8adXRkq3sfeT9XSAXl1WHL+kP82ei8
            niX53VDPo9gZYHb5/W5gbKXxW+DyaP4+XL1NDz1aoWI0ySgiOvzRjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T13:51:22Z"
    mac: ENC[AES256_GCM,data:SS1jaSReIAkMV29WqNj5fWIk0hk+rPg9TCNAyzmzuwiVoRxrIAXv2cQUWeFJ43AuHIB5cJqH548No7XQrqexGyhUr/mi0uhfqihRc74OjyJqelnKlUbJRR+82oKF4EMscjVgQ+SouzH9isEiXitjB+j+nsDFdIRPNMTI+YIfi0M=,iv:rRgogwmIFgsFneA9L5OFVmVCzq3ecrVcaCRCS0bP614=,tag:6HATtMUii72u72idG+MBMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
