apiVersion: v1
kind: Secret
metadata:
    name: proton
    namespace: media
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:Ug67AKjhIu7gfnz/Ku9UxOXKiaEg6ktdGERwJ/qWK9IL3bi4d6Z7XKnNPjeX5Cfg5T6Un+Crkz5opyiRq/vpmV0pJB6Wd/6HYWIabsGAGPpOkPMJyQAXO7Qd9JEQ6ZJK3hzpbU2pMIEfZhDHCFhHPvYUlA1dVsSa+/vdCjxrHAwP8PhOU3iLSU4/mLlvRFXyuH41kUT6UTZCWgLgES1fbxgOv0dw/6bj8BsSYg8icl1VRaoU/8STCCrx+qbDJ0yMBrJiDcmbu/WwdWdxfv0Z2cL0CSdh+BGbXsbqSk5meJAEHvkZlkQ7eztq19Of4wHoaly8Fiit4ul9MmXL9oO0rm7DWNhQl28gSkT2td3vTsCzRqr14f7lavm3AzXE7oa/WcWx1Y+fYevRknvyknIMzOzAw3yTWO2z3vKdzst26FSPflKLdvjmHihG0IpeF8tbyNoQ1K9/Yw1Ke2MspCR747XvsbCUL4zQ0iEEYi++3obnCntfGfGHooC4+2xLZkRnh/lEzIaxvOA=,iv:QaxXgpJhJOemfJpz4TYnXA8TrghA9BlJfXoptHwsnU8=,tag:0EaGTzq7R+5tH6Ate5C3AA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQnRrVW9xY1Jvczd6T2k3
            NUxLUlZENGdiWWxFUHhPcmZ3SUNaSEhoS1RRCk1UVWdhUk93ekxXd0ZWNGtyVEtu
            Y3lMK0NNZmo1UWJZd1Q1TFJta29RbjQKLS0tIFhCcnJlQy9DQzRoNzRCUVNsNEJB
            NDlLYjU5a3pVWTJuRm5lMGVOc21ScXMKcFmk6LS+SsFwNKzrw00fg/jHPQNBCugu
            Ry7oWd79x1oNp8mMu81ab/QBGjIJaxA9biooz/khSjiYQmDjNwJxMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T04:46:02Z"
    mac: ENC[AES256_GCM,data:+h0TxBbRLEP07upw8E7sz2Adv6ISt3RjqZ4yBeP8y9kxTmw4dp85z1Coq6qA9kIamB7d5X3uA1iEBlC4rL7LIcoMf50WSdChCothmLS9mhI9wna0tT+oRntZWw6++G9xdWNcwlJuFPlhHeGQ/KGfH8XFcNKrB86mjDjjqezaS9g=,iv:IqnQjifbnIpqQjLPA/CM6o1ndd5RrlZwB+f5/V+3ZCg=,tag:uwARPZLbv8bProfxVc7fbA==,type:str]
    version: 3.13.1
