apiVersion: v1
kind: Secret
metadata:
    name: proton-prowlarr
    namespace: media
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:RPp7ZjXYGeu2ttCabtzK0vLWDTv8/5yWhlc3YLs8nN0KKH/4lyUhrez1BsKX6iYkH1Dr9a6LCj6Q1mHK+BmMSQ9JSlJtRhMKeESLjsJljE8zfmE7Z81A+AtOyE81Szenwdx6+XxQ+olMDc/AFoooFwg7uwMfEtL1HxbqmZVbWHYWKiq9pwn/jBpmGt+wt+4aEm9RZyFcwHUIbbhaRzX7MUDPwFAiKwQWeZ7S+25d3NpV3L4p2kqEaONBqgDR9UMPXZqf2fQIaRPpAfEvmD8xs0OKzfq5Cg2Gq8rH7pgNr7OgibFIRn+3fS07O9xTHsFrqhQYR8GSnK1HenplcGDWz2LkgXStpf85DNlIEZXb0tSbszKvrtItLHXD7vtFV1yYNrzFjpwfH0yinY6K1fCjH8BRwmZEnBhtwxKvwJ/ksy1SEfDyxBHMT41mY6bdSZn4z9UXySpNxIPhzc91erVuMVQE+YDgfnC0Evb66bquzvz2F4Qr2MzN1AYJB/srwgXS/Qk31QbByujDQH9vgo1a/A1jfQSB29FSxRI1Yr4x5myEfE3tmsy6nfzQe5vaKLL7iO+/aINt/Wp8cGP3Zg2GVmlYIAnvJBbbouSolAF5p0yIhYpsvF95Htrmdv17qz/aA2kNVeUURCISiYSxqfd9Ia2b5FGqEFRXpCzHFceYmK5Ers2q77ruofqU4HNIK4E=,iv:XtGF88h70u295Ks+cXXru+x7V4We71SJCc9xTkO/ow8=,tag:vZwXqNl5y65liVXGiJ8gGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b0NmYzQ5MWpuZzRuT091
            WEwxOGoxZFVpZFBFVmxycWtpSDhGaDhlZEVrCmdJWFl4WGloQ1htVWIxNEpuWk9r
            SlJ5akFuNkIweXArbDNoQmE0aklNQ3cKLS0tIC81anNFZmRrL2h6NEZoa0h6N24y
            NHdGQjFuK2dpVWlLVFB4M09PRk5tWDQKpJfvFC3J/5ZCK0TYBq3UPWja7voK8Kif
            Ad65syuT/PHV8SuOFQXT0Bkl0e2i+2SD6+q+OT12zZooli0u/0jjZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T06:21:46Z"
    mac: ENC[AES256_GCM,data:3HdpPRHuSrKnX2MRd3mlnmpANfAVfpV1+HRDt7//HYLV/ETVc4J0PaZPqeVOcBI6Qx/ZY4usGDv/BVF5753czgyeMLw4JsrxDPM1rqKeZzFEGSiGtE0IkzqEq+02vgDMSKXlFHnjQjGs++6VQcRN2GBz6nhjpxdjNEupaQG/t5E=,iv:6MLWhDxAA9EK4APwzToXQ9LTwLeKPzd1ET65cl6VCPw=,tag:BDpopDc9FQ911FHnqpXwcg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: proton-sabn
    namespace: media
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:H0ZrsljuGJjSG7yjTFHpmiPBvXKEZhHe4pD2598hR1j16otkzif6BY8WnqIzsGzxQ8m/yh65rQBEca+K8gX/irjTZi6vlA4W+NIppRfNQ/2nGHqHbCtz3shwFH/rFAX2N57S/iDohscDyezCDoIBmeKBFyYGCO7pJWjKel7h5g7AuDVD+3NDn3aVp2yBlqau9eIBbA+V05gWg5+k3BkAiwgoUqwZdWc8w3WF2eYNVAVpwbQl+Ee23C9B5NsCaCzYrU6ioYJMjZzNJQlH2zU2qoLl6ynocc6YlfK4sc29f2Ym+1h1ZT2xfv1oIVHhH+P8yX1Bx9bSUDNFh63+dvtynRYedFhLeABszYu10QQ8147MkxZcC7ScFs3WnfkKl7YbZWzGHLftDx+D6zCkQnxT23tzc4hhS4ybB+sqb4IHee/6y/3CVlLPAManb+G0R5vCXI9H+IPJorG5zr1KOpe6boUtmHZ5DpodIGMgFlMuEM87mpd+lRGAy/NuKxGXUMmuiLhk3YwXXS1zDu6WPcYQsWdwNbxJCaLYrMWgd4c4oxq398sIFqPTMjVvsxJORlhxEUd+WIJa9kv5ZwUU4rDu7aDEYsOPHZShoa9Xte6pFvE8IEvjHTL9UnWYun/l6ijaWWyv2ncF8xar0NNmZr5tmdvL7M7tzFg3jO9EC+7uRaGghaK4EsNe7IWX1ANe,iv:fktwHhcuPmY7k4HSACwGkhr8+ZTy+wmclIiGwMguJnY=,tag:IlD/JJc9Tx9D7YtoDRA6lQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b0NmYzQ5MWpuZzRuT091
            WEwxOGoxZFVpZFBFVmxycWtpSDhGaDhlZEVrCmdJWFl4WGloQ1htVWIxNEpuWk9r
            SlJ5akFuNkIweXArbDNoQmE0aklNQ3cKLS0tIC81anNFZmRrL2h6NEZoa0h6N24y
            NHdGQjFuK2dpVWlLVFB4M09PRk5tWDQKpJfvFC3J/5ZCK0TYBq3UPWja7voK8Kif
            Ad65syuT/PHV8SuOFQXT0Bkl0e2i+2SD6+q+OT12zZooli0u/0jjZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T06:21:46Z"
    mac: ENC[AES256_GCM,data:3HdpPRHuSrKnX2MRd3mlnmpANfAVfpV1+HRDt7//HYLV/ETVc4J0PaZPqeVOcBI6Qx/ZY4usGDv/BVF5753czgyeMLw4JsrxDPM1rqKeZzFEGSiGtE0IkzqEq+02vgDMSKXlFHnjQjGs++6VQcRN2GBz6nhjpxdjNEupaQG/t5E=,iv:6MLWhDxAA9EK4APwzToXQ9LTwLeKPzd1ET65cl6VCPw=,tag:BDpopDc9FQ911FHnqpXwcg==,type:str]
    version: 3.13.1
