apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
    namespace: media
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:uBra/rXyhX8OvJKLEPa3bA==,iv:SVmcHoEpew6qsMqqoqefKtmyy89U36SlwEWstPTqNvE=,tag:3h9Jj+7ewq0vGjsNOC6yoA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:iEJ3eV9472+GEf6q2j6mqw==,iv:Tcu1oLfHBBX7521edpMQpnqXwI8cIDo8GxU2FZK6OJs=,tag:hXHUvIzFjBzBH6M1sW8ZHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOFVBWHF6MW9NTGgvT3lI
            c3FzL3MwTWF0dDRsS1lmYldlSWJJYjNDekJvCnhqem53Nm1nMDVPTkp6QXBlbHAv
            UjJkMEo4SStoeTJsV2ZoaDFYdDRibG8KLS0tIEo3K0Y0MFhyNkdRSFFYalEvV0dx
            S1dxS3UxK00ybDkwM1Y0V2REdmhzU28KuuYquhz/P85xakYPEH4rSSR6dA8Mbm0J
            RjDNaMwFUKlezXmfU77BreosRenDjTJ/EjSTtw+B5+4eZgkvseTsVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18053rs2m62my8fstp687lxautwk099y08tgw5r4l6d33u8rzkads2apepn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T04:46:06Z"
    mac: ENC[AES256_GCM,data:RJAk3VV8AplwXXhIpyKISBkf99+GpUz/+up+sBTA8OF2DMnSlzn4rbO503OcYgD/mR0Hg4yAWbuiNCn+y3u32XV8x/dQ/uM3rLDwgcLSLbyhba9tkDk2krnYbnsC1nQgIPxCwuSsf0z0SCAPvmvrmtt325TyHjVmhX87w7+G/5M=,iv:bsmRE/9peajpMTPGCo9QpUpS5qjCHW39+LdYMIWQm8A=,tag:jOi8pIQEYsaJfgXaAIxizA==,type:str]
    version: 3.13.1
